// Regression: in a protein a hydrogen has ONE heavy neighbour — the impossible
// "bonds" of the autogenerated structures (HD2-CE, HD3-CE, HD2-NE, HD3-NE,
// HG2-CD, HG3-CD, HB2-CG, HB3-CG) must never be drawn again.
//
// Why they appeared: the builder placed the two protons of a methylene carbon with
// fixed +-120 deg torsions, which are tetrahedral only against the atom the frame
// was built on. Against the NEXT heavy atom of the side chain (or against the ring
// nitrogen of a proline) one proton sat 0.73 to 1.28 A from an atom it is not
// bonded to, and NGL binds every H-heavy pair inside the covalent window of
// AtomProxy.connectedTo (radii + 0.3, i.e. 0.57 - 1.37 A for H-C) — on top of the
// file's own CONECT records, because the PDB parser's default is inferBonds:'all'.
//
// Run: node _protein_hydrogen_bonds_test.mjs
import { readFileSync } from 'node:fs';
import { rebuildProteinHydrogenCoords } from './src/utils/rebuildProteinHydrogens.js';
import { keepOnlyOneHeavyBondPerHydrogen, enforceOneHeavyBondPerHydrogen, hydrogenBondLimit } from './src/utils/hydrogenBondRule.js';

let failures = 0;
const ok = (cond, msg) => {
  if (cond) console.log('ok   ' + msg);
  else { failures++; console.error('FAIL ' + msg); }
};

// ---- the builder, extracted out of the JSX the way the other suites do ---------
const src = readFileSync('src/components/NMRSections.jsx', 'utf8');
const extract = (name) => {
  const start = src.indexOf(`const ${name} = `);
  if (start === -1) throw new Error('missing ' + name);
  const bodyStart = start + `const ${name} = `.length;
  let depth = 0;
  let i = bodyStart;
  for (; i < src.length; i++) {
    const ch = src[i];
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') depth--;
    else if (ch === ';' && depth === 0) break;
  }
  if (i >= src.length) throw new Error('unterminated ' + name);
  return src.slice(start, i + 1) + '\n';
};
const order = ['_vecSub', '_vecAdd', '_vecScale', '_vecDot', '_vecCross', '_vecNorm', '_vecNormalize', '_deg2rad', 'nerfPlace', '_padLeft', '_padRight', '_formatAtomName', '_fmtNum', 'pdbAtomLine', 'AA_1_TO_3', 'PROTEIN_BB', 'SS_TORSIONS', 'ssTorsionAt', '_ringClose', 'placeSidechainAtoms', 'buildProteinBackbone', 'buildProteinHCoords', 'proteinSequenceToPdbText'];
let code = '';
order.forEach((n) => { code += extract(n); });
const { proteinSequenceToPdbText, buildProteinHCoords } = new Function(code + '\nreturn { proteinSequenceToPdbText, buildProteinHCoords };')();

// ---- parse a PDB text ---------------------------------------------------------
const parsePdb = (text) => {
  const atoms = [];
  const conect = new Map();
  String(text || '').split(/\r?\n/).forEach((line) => {
    const rec = line.slice(0, 6).trim();
    if (rec === 'ATOM' || rec === 'HETATM') {
      const name = line.slice(12, 16).trim();
      atoms.push({
        serial: parseInt(line.slice(6, 11), 10),
        name,
        resName: line.slice(17, 20).trim(),
        chain: line.slice(21, 22).trim(),
        resSeq: parseInt(line.slice(22, 26), 10),
        x: parseFloat(line.slice(30, 38)),
        y: parseFloat(line.slice(38, 46)),
        z: parseFloat(line.slice(46, 54)),
        element: (line.slice(76, 78).trim() || name[0]).toUpperCase(),
      });
    } else if (rec === 'CONECT') {
      const s = parseInt(line.slice(6, 11), 10);
      const list = conect.get(s) || [];
      for (let i = 11; i + 5 <= line.length; i += 5) {
        const v = parseInt(line.slice(i, i + 5), 10);
        if (Number.isFinite(v)) list.push(v);
      }
      conect.set(s, list);
    }
  });
  const bySerial = new Map(atoms.map((a) => [a.serial, a]));
  const bondsOf = (a) => {
    const partners = [];
    (conect.get(a.serial) || []).forEach((s) => { const b = bySerial.get(s); if (b) partners.push(b); });
    // a CONECT line may be written from either end: the pair is what matters
    atoms.forEach((b) => {
      if (b === a) return;
      if ((conect.get(b.serial) || []).includes(a.serial)) partners.push(b);
    });
    return partners;
  };
  return { atoms, conect, bySerial, bondsOf };
};

const dist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
// NGL's own window: AtomProxy.connectedTo reads covalent radii + 0.3 (upper) and
// covalent radii - 0.5 (lower).
const RAD = { H: 0.31, C: 0.76, N: 0.71, O: 0.66, S: 1.05, SE: 1.16 };
const windowOf = (e1, e2) => ({ lo: Math.max(0, (RAD[e1] || 0.77) + (RAD[e2] || 0.77) - 0.5), hi: (RAD[e1] || 0.77) + (RAD[e2] || 0.77) + 0.3 });
const withinBondWindow = (h, g) => {
  const w = windowOf(h.element, g.element);
  const d = dist(h, g);
  return d < w.hi && d > w.lo;
};

/** Every hydrogen that is inside a bond window of a heavy atom it is not bonded to. */
const impossibleBonds = ({ atoms, bondsOf }) => {
  const out = [];
  atoms.filter((a) => a.element === 'H').forEach((h) => {
    const bondedSerials = new Set(bondsOf(h).filter((b) => b.element !== 'H').map((b) => b.serial));
    atoms.forEach((g) => {
      if (g.element === 'H' || g.serial === h.serial) return;
      if (g.chain !== h.chain || g.resSeq !== h.resSeq) return;
      if (bondedSerials.has(g.serial)) return;
      if (withinBondWindow(h, g)) out.push(h.name + h.resSeq + '(' + h.resName + ')-' + g.name + ' ' + dist(h, g).toFixed(2) + ' A');
    });
  });
  return out;
};

// ---- 1. the model the viewer draws -------------------------------------------
const seq = 'ACDEFGHIKLMNPQRSTVWY';
const pdb = proteinSequenceToPdbText(seq, '');
const model = parsePdb(pdb);
ok(model.atoms.length === 324, 'builder atoms = ' + model.atoms.length + ' (expected 324)');

const bad = impossibleBonds(model);
ok(bad.length === 0, 'no hydrogen sits inside a bond window of a second heavy atom (' + bad.length + ')'
  + (bad.length ? ' -> ' + bad.slice(0, 12).join(', ') : ''));

// the exact pairs the user reported must be gone, for both a lysine and an arginine
const pair = (aName, resName, aRes, bName, bRes) => {
  const A = model.atoms.find((x) => x.name === aName && x.resName === resName && x.resSeq === aRes);
  const B = model.atoms.find((x) => x.name === bName && x.resSeq === bRes);
  if (!A || !B) return null;
  return { A, B, bonded: model.bondsOf(A).includes(B), d: dist(A, B) };
};
const lysSeq = seq.indexOf('K') + 1;
const argSeq = seq.indexOf('R') + 1;
[['HB2', 'CG'], ['HB3', 'CG'], ['HG2', 'CD'], ['HG3', 'CD'], ['HD2', 'CE'], ['HD3', 'CE']].forEach(([h, heavy]) => {
  const p = pair(h, 'LYS', lysSeq, heavy, lysSeq);
  if (!p) { failures++; console.error('FAIL LYS ' + h + '-' + heavy + ' not found in the built model'); return; }
  ok(!p.bonded && p.d > 1.5, 'LYS ' + h + '-' + heavy + ' is NOT a bond (' + p.d.toFixed(2) + ' A)');
});
['HD2', 'HD3'].forEach((h) => {
  const p = pair(h, 'ARG', argSeq, 'NE', argSeq);
  if (!p) { failures++; console.error('FAIL ARG ' + h + '-NE not found'); return; }
  ok(!p.bonded && p.d > 1.5, 'ARG ' + h + '-NE is NOT a bond (' + p.d.toFixed(2) + ' A)');
});
const proSeq = seq.indexOf('P') + 1;
const proHd3 = pair('HD3', 'PRO', proSeq, 'N', proSeq);
if (proHd3) ok(proHd3.d > 1.5, 'PRO HD3-N is NOT a bond (' + proHd3.d.toFixed(2) + ' A)');

// the real bonds are still there, at the right length
[['HB2', 'CB'], ['HB3', 'CB'], ['HG2', 'CG'], ['HD2', 'CD'], ['HE2', 'CE']].forEach(([h, heavy]) => {
  const p = pair(h, 'LYS', lysSeq, heavy, lysSeq);
  if (!p) { failures++; console.error('FAIL LYS ' + h + '-' + heavy + ' missing'); return; }
  ok(p.bonded && Math.abs(p.d - 1.09) < 0.02, 'LYS ' + h + '-' + heavy + ' is still a 1.09 A bond (' + p.d.toFixed(2) + ' A)');
});

// the closest H...heavy contact that is NOT a bond stays far outside the window
let minNonBond = Infinity;
let minWhat = '';
model.atoms.filter((a) => a.element === 'H').forEach((h) => {
  const bondedSerials = new Set(model.bondsOf(h).map((b) => b.serial));
  model.atoms.forEach((g) => {
    if (g.element === 'H' || g.serial === h.serial) return;
    if (g.chain !== h.chain || g.resSeq !== h.resSeq) return;
    if (bondedSerials.has(g.serial)) return;
    const d = dist(h, g);
    if (d < minNonBond) { minNonBond = d; minWhat = h.name + h.resSeq + '-' + g.name; }
  });
});
ok(minNonBond > 1.5, 'closest non-bonded H...heavy contact = ' + minNonBond.toFixed(2) + ' A (' + minWhat + ')');

// ---- 2. the same correction in the hydrogen-rebuild path ----------------------
const rebuilt = rebuildProteinHydrogenCoords(pdb);
ok(rebuilt.ok, 'rebuildProteinHydrogenCoords accepted the generated model (' + rebuilt.rebuilt + ' H rebuilt)');
const rebuiltBad = impossibleBonds(parsePdb(rebuilt.text));
ok(rebuiltBad.length === 0, 'rebuilt hydrogens have no impossible bond either (' + rebuiltBad.length + ')'
  + (rebuiltBad.length ? ' -> ' + rebuiltBad.slice(0, 8).join(', ') : ''));

// the rebuild must agree with the builder's own coordinates (the mirror is exact)
const expected = buildProteinHCoords(seq, '');
let mismatches = 0;
let checked = 0;
parsePdb(rebuilt.text).atoms.forEach((a) => {
  if (a.element !== 'H') return;
  const want = expected[a.resSeq - 1] && expected[a.resSeq - 1][a.name];
  if (!want) return;
  checked++;
  if (Math.hypot(a.x - want[0], a.y - want[1], a.z - want[2]) > 0.01) mismatches++;
});
ok(checked > 150 && mismatches === 0, 'rebuild matches the builder on ' + checked + ' hydrogens (' + mismatches + ' mismatches)');

// ---- 3. the rule: one heavy neighbour per hydrogen ---------------------------
// A lysine-like fragment with the PRE-FIX clash distances (HB3 1.28 A from CG) —
// exactly the geometry the builder used to produce.
const frag = [
  { element: 'C', name: 'CB', x: 0, y: 0, z: 0 },
  { element: 'C', name: 'CG', x: 1.53, y: 0, z: 0 },
  { element: 'H', name: 'HB2', x: -1.09, y: 0, z: 0 },       // 1.09 from CB only
  { element: 'H', name: 'HB3', x: 0.618, y: 0.898, z: 0 },    // 1.09 from CB, 1.28 from CG
];
const fragBonds = [[0, 1], [0, 2], [0, 3], [1, 3]];  // CB-CG, CB-HB2, CB-HB3, CG-HB3
const keptFrag = keepOnlyOneHeavyBondPerHydrogen(frag, fragBonds);
const keptPairs = keptFrag.map((k) => fragBonds[k].join('-'));
ok(!keptPairs.includes('1-3'), 'rule drops HB3-CG (kept: ' + keptPairs.join(' ') + ')');
ok(keptPairs.includes('0-3') && keptPairs.includes('0-2'), 'rule keeps each hydrogen on its one shortest heavy bond');
ok(keptPairs.includes('0-1'), 'rule leaves heavy-heavy bonds alone');
ok(hydrogenBondLimit('H', 'C') === 1.37 && hydrogenBondLimit('H', 'N') === 1.32,
  'bond limit mirrors NGL (H-C ' + hydrogenBondLimit('H', 'C') + ' A, H-N ' + hydrogenBondLimit('H', 'N') + ' A)');

const goodBonds = [[0, 1], [0, 2], [0, 3]];
ok(keepOnlyOneHeavyBondPerHydrogen(frag, goodBonds).length === goodBonds.length, 'a correct graph is untouched');

// an arginine-like fragment: HD2 hangs on CD (1.09 A) and NE is the next atom (1.28 A)
const arg = [
  { element: 'C', name: 'CD', x: 0, y: 0, z: 0 },
  { element: 'N', name: 'NE', x: 1.46, y: 0, z: 0 },
  { element: 'H', name: 'HD2', x: 0.618, y: 0.898, z: 0 },   // 1.09 from CD, 1.28 from NE
];
const argKept = keepOnlyOneHeavyBondPerHydrogen(arg, [[0, 1], [0, 2], [1, 2]]);
ok(!argKept.includes(2), 'rule drops HD2-NE and keeps HD2-CD of an arginine');

// and the applier compacts a structure's bond store (mimicked — no GL context)
const fakeStructure = (atoms, bonds) => ({
  atomCount: atoms.length,
  bondStore: {
    count: bonds.length,
    atomIndex1: Uint32Array.from(bonds.map((b) => b[0])),
    atomIndex2: Uint32Array.from(bonds.map((b) => b[1])),
    bondOrder: Uint8Array.from(bonds.map(() => 1)),
  },
  getAtomProxy() {
    if (!this._proxy) {
      const a = atoms;
      this._proxy = {
        index: 0,
        get x() { return a[this.index].x; },
        get y() { return a[this.index].y; },
        get z() { return a[this.index].z; },
        get element() { return a[this.index].element; },
        get atomname() { return a[this.index].name || a[this.index].element; },
      };
    }
    return this._proxy;
  },
});
const st = fakeStructure(frag, fragBonds);
const dropped = enforceOneHeavyBondPerHydrogen(st);
const left = [];
for (let i = 0; i < st.bondStore.count; i++) left.push(st.bondStore.atomIndex1[i] + '-' + st.bondStore.atomIndex2[i]);
ok(dropped === 1 && st.bondStore.count === 3, 'applier drops 1 of 4 bonds (dropped=' + dropped + ', left=' + st.bondStore.count + ')');
ok(!left.includes('1-3'), 'applier surviving graph: ' + left.join(' '));
ok(enforceOneHeavyBondPerHydrogen(st) === 0, 'applier is idempotent');
ok(enforceOneHeavyBondPerHydrogen(null) === 0, 'applier tolerates a missing structure');

// ---- 4. the viewer applies the rule before anything reads the graph -----------
const viewer = readFileSync('src/components/NMRMoleculeViewer.jsx', 'utf8');
ok(/import \{[^}]*enforceOneHeavyBondPerHydrogen[^}]*\} from '\.\.\/utils\/hydrogenBondRule'/.test(viewer),
  'viewer imports the rule');
const applied = viewer.split('enforceOneHeavyBondPerHydrogen(').length - 1;
ok(applied >= 4, 'viewer applies it on every load path (' + applied + ' call sites)');
const mainLoad = viewer.indexOf("component = await stage.loadFile(blob, { ext: loadRequest.ext || 'pdb' });");
const mainCall = viewer.indexOf('enforceOneHeavyBondPerHydrogen(component)');
const firstRep = viewer.indexOf('applyCurrentStyleTo(component', mainLoad);
ok(mainCall > mainLoad && (firstRep === -1 || mainCall < firstRep),
  'the main load prunes the graph BEFORE the first representation is built');

console.log(failures === 0 ? '\nPASS' : '\nFAIL (' + failures + ')');
process.exit(failures === 0 ? 0 : 1);
