// Regression: in a protein, two heavy atoms that share a heavy neighbour are NEVER
// bonded — the impossible "bonds" of the autogenerated structures (the reported
// CD-CA and CD-CB of a proline) must never be drawn again.
//
// Why they appeared: the ring closure of the proline side chain (_ringClose in
// NMRSections.jsx) enumerated the two solutions of the circle–circle intersection
// that lie PERPENDICULAR to the direction of the answer — a fixed 90° away, both of
// them inside the CA/CB corner of the ring — and broke the tie with
// `|c1 - avoid| > |c2 - avoid|`, a comparison that is ALWAYS a tie because `perp` is
// built from `avoid` itself. The side was decided by floating-point noise, so CD
// could land 1.59 A from CA and 1.77 A from CB: inside the covalent window of
// AtomProxy.connectedTo (0.76 + 0.76 + 0.3 = 1.82 A for a C–C pair). The PDB parser's
// default `inferBonds:'all'` ADDS a bond for every pair inside that window, on top of
// the file's own CONECT records, and the viewer drew the two bars.
//
// This file pins down both halves of the fix: the GEOMETRY (a proline ring closes on
// a near-regular pentagon, and no heavy–heavy contact of the whole model sits inside
// a bond window) and the DRAWING RULE (proteinBondRule.js), which removes such a
// bond from the graph whatever the file said.
//
// Run: node _protein_heavy_bonds_test.mjs
import { readFileSync } from 'node:fs';
import { impossibleProteinBondIndices, keepOnlyCovalentProteinBonds, enforceCovalentProteinBonds, isProteinResidue } from './src/utils/proteinBondRule.js';

let failures = 0;
const ok = (cond, msg) => {
  if (cond) console.log('ok   ' + msg);
  else { failures++; console.error('FAIL ' + msg); }
};

// ---- the builder, extracted out of the JSX the way the other suites do ---------
const src = readFileSync('src/components/NMRSections.jsx', 'utf8');
const extract = (name) => {
  const start = src.indexOf(`const ${name} = `);
  if (start === -1) throw new Error('missing ' + name);
  const bodyStart = start + `const ${name} = `.length;
  let depth = 0;
  let i = bodyStart;
  for (; i < src.length; i++) {
    const ch = src[i];
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') depth--;
    else if (ch === ';' && depth === 0) break;
  }
  if (i >= src.length) throw new Error('unterminated ' + name);
  return src.slice(start, i + 1) + '\n';
};
const order = ['_vecSub', '_vecAdd', '_vecScale', '_vecDot', '_vecCross', '_vecNorm', '_vecNormalize', '_deg2rad', 'nerfPlace', '_padLeft', '_padRight', '_formatAtomName', '_fmtNum', 'pdbAtomLine', 'AA_1_TO_3', 'PROTEIN_BB', 'SS_TORSIONS', 'ssTorsionAt', '_ringClose', 'placeSidechainAtoms', 'buildProteinBackbone', 'proteinSequenceToPdbText'];
let code = '';
order.forEach((n) => { code += extract(n); });
const B = new Function(code + '\nreturn { proteinSequenceToPdbText, buildProteinBackbone, placeSidechainAtoms, _ringClose, _vecSub, _vecAdd, _vecScale, _vecDot, _vecNorm, _vecNormalize, _vecCross };')();

// ---- parse a PDB text (ATOM records + CONECT pairs, in file order) --------------
const parsePdb = (text) => {
  const atoms = [];
  const conect = new Map();
  String(text || '').split(/\r?\n/).forEach((line) => {
    const rec = line.slice(0, 6).trim();
    if (rec === 'ATOM' || rec === 'HETATM') {
      atoms.push({
        index: atoms.length,
        serial: parseInt(line.slice(6, 11), 10),
        name: line.slice(12, 16).trim(),
        resName: line.slice(17, 20).trim(),
        resSeq: parseInt(line.slice(22, 26), 10),
        element: (line.slice(76, 78).trim() || line.slice(12, 16).trim()[0]).toUpperCase(),
        x: parseFloat(line.slice(30, 38)),
        y: parseFloat(line.slice(38, 46)),
        z: parseFloat(line.slice(46, 54)),
      });
    } else if (rec === 'CONECT') {
      const s = parseInt(line.slice(6, 11), 10);
      const list = conect.get(s) || [];
      for (let i = 11; i + 5 <= line.length; i += 5) {
        const v = parseInt(line.slice(i, i + 5), 10);
        if (Number.isFinite(v)) list.push(v);
      }
      conect.set(s, list);
    }
  });
  const bySerial = new Map(atoms.map((a) => [a.serial, a]));
  const pairs = new Set();
  conect.forEach((list, s) => list.forEach((t) => pairs.add([s, t].sort((a, b) => a - b).join('|'))));
  const bondsOf = (a) => {
    const out = [];
    pairs.forEach((key) => {
      const [s, t] = key.split('|').map(Number);
      const other = s === a.serial ? bySerial.get(t) : (t === a.serial ? bySerial.get(s) : null);
      if (other) out.push(other);
    });
    return out;
  };
  return { atoms, conect, bySerial, bondsOf, pairs };
};

const dist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
// NGL's own window: AtomProxy.connectedTo reads covalent radii + 0.3 (upper) and
// covalent radii - 0.5 (lower).
const RAD = { H: 0.31, C: 0.76, N: 0.71, O: 0.66, S: 1.05 };
const windowOf = (e1, e2) => ({ lo: Math.max(0, (RAD[e1] || 0.77) + (RAD[e2] || 0.77) - 0.5), hi: (RAD[e1] || 0.77) + (RAD[e2] || 0.77) + 0.3 });


// ---- 1. the builder's own model: no heavy–heavy contact inside a bond window ----
const seq = 'ACDEFGHIKLMNPQRSTVWY';
const pdb = B.proteinSequenceToPdbText(seq, '');
const model = parsePdb(pdb);
ok(model.atoms.length === 325, 'builder atoms = ' + model.atoms.length + ' (expected 325: the 324 of before plus the C-terminal OXT of §1ter)');

const isH = (a) => a.element === 'H' || a.element === 'D';
const heavy = model.atoms.filter((a) => !isH(a));
const impossible = [];
heavy.forEach((a, ai) => heavy.slice(ai + 1).forEach((b) => {
  if (a.chain !== b.chain) return;                              // the viewer only draws within one component
  const w = windowOf(a.element, b.element);
  const d = dist(a, b);
  if (d >= w.hi || d <= w.lo) return;
  if (model.bondsOf(a).includes(b)) return;                     // a declared bond may legitimately be that short
  impossible.push(`${a.name}@${a.resSeq}(${a.resName})-${b.name}@${b.resSeq} ${d.toFixed(2)} A`);
}));
ok(impossible.length === 0, 'no heavy–heavy pair of the built model sits inside a covalent window ('
  + impossible.length + ')' + (impossible.length ? ' -> ' + impossible.slice(0, 8).join(', ') : ''));

// the exact pairs the user reported: a proline's CD is not bonded to its CA / CB
const proSeq = seq.indexOf('P') + 1;
const atomOf = (name, resSeq) => model.atoms.find((a) => a.name === name && a.resSeq === resSeq);
[['CD', 'CA'], ['CD', 'CB']].forEach(([x, y]) => {
  const a = atomOf(x, proSeq);
  const b = atomOf(y, proSeq);
  if (!a || !b) { failures++; console.error('FAIL PRO ' + x + '-' + y + ' not found in the built model'); return; }
  const d = dist(a, b);
  ok(!model.bondsOf(a).includes(b) && d > 1.9,
    `PRO ${x}-${y} is NOT a bond (${d.toFixed(2)} A; CONECT gives CD ${model.bondsOf(a).length} neighbours)`);
});

// every CD of the model, in fact: never inside a C–C window of its own CA / CB
const near = [];
model.atoms.filter((a) => /^CD\d?$/.test(a.name)).forEach((cd) => {
  ['CA', 'CB'].forEach((nm) => {
    const p = atomOf(nm, cd.resSeq);
    if (p && dist(cd, p) < windowOf('C', 'C').hi) near.push(`${cd.name}@${cd.resSeq}-${nm} ${dist(cd, p).toFixed(2)}`);
  });
});
ok(near.length === 0, 'no residue has its CD inside a C–C window of CA or CB' + (near.length ? ' -> ' + near.join(', ') : ''));

// ---- 1ter. the C-terminus is a carboxylate ------------------------------------
// The user's report, word for word: "The pH setting is wrong. it gives me a charge of +36 at
// pH 7 for the peptide: SIIGIIMGILGNIPQVIQIIMSIVKAFKGNK. At pH 7 it should be +3!"  Part of
// that +4-vs-+3 gap was the model itself: the built chain carried NO acid at all — the
// carboxylate every real peptide ends in was missing — so no pH could ever read below its
// four bases (three lysines + the N-terminus).  It is written now: OXT, with NO proton on it,
// exactly like the carboxylates of Asp and Glu (see buildProteinBackbone), so the field reads
// a CARBOXYLATE (pKa 3.9) and titrates it to −1 at pH 7.
const lastRes = model.atoms.reduce((m, a) => Math.max(m, a.resSeq), 0);
const atomAt = (name, resSeq) => model.atoms.find((a) => a.name === name && a.resSeq === resSeq);
const cTerm = atomAt('C', lastRes);
const oTerm = atomAt('O', lastRes);
const oxt = atomAt('OXT', lastRes);
ok(!!oxt, `the last residue of the built chain carries an OXT (residue ${lastRes})`);
ok(oxt && model.bondsOf(cTerm).includes(oxt),
  '…and it is BONDED to the carbonyl carbon by a real CONECT record (that record is what makes the group a carboxylate for the field)');
ok(model.bondsOf(cTerm).length === 3,
  `…the terminal carbon has exactly three neighbours (${model.bondsOf(cTerm).map((a) => a.name).join('/')}) — it is an sp2 carboxyl carbon, nothing else hangs on it`);
const corner = (a, b, c) => {
  const u = [a.x - b.x, a.y - b.y, a.z - b.z];
  const v = [c.x - b.x, c.y - b.y, c.z - b.z];
  const n = (w) => Math.hypot(w[0], w[1], w[2]);
  return Math.acos(Math.max(-1, Math.min(1, (u[0] * v[0] + u[1] * v[1] + u[2] * v[2]) / (n(u) * n(v))))) * 180 / Math.PI;
};
ok(oxt && Math.abs(dist(cTerm, oxt) - dist(cTerm, oTerm)) < 0.002,
  `…with the SAME C–O length as the carbonyl oxygen (${dist(cTerm, oTerm).toFixed(3)} / ${dist(cTerm, oxt).toFixed(3)} A — the file rounds to 1/1000 Å)`);
ok(oxt && Math.abs(corner(oTerm, cTerm, oxt) - 119.0) < 0.6,
  `…and the planar-carboxylate corner O–C–OXT = ${corner(oTerm, cTerm, oxt).toFixed(2)}° (the two C–O are 180° apart about the CA–C axis)`);
ok(oxt && Math.abs(corner(atomAt('CA', lastRes), cTerm, oxt) - 120.5) < 0.6,
  `…CA–C–OXT = ${corner(atomAt('CA', lastRes), cTerm, oxt).toFixed(2)}° — the third sp2 angle`);
ok(!model.atoms.some((a) => a.name === 'HXT'),
  '…and NO proton is written on it (the ionised form, as for Asp and Glu: the pH is what charges it)');
ok(oxt && model.atoms.filter(isH).every((h) => dist(h, oxt) > 1.3),
  '…no hydrogen of the model sits within a bond window of the OXT either (the terminus cannot be read as a COOH)');


// ---- 2. the proline ring itself: a pentagon, not a folded chain ----------------
const bb = B.buildProteinBackbone('APA', '')[1];
const sidechain = B.placeSidechainAtoms('P', bb);
const pro = { N: bb.N, CA: bb.CA, C: bb.C, O: bb.O, CB: bb.CB };
sidechain.atoms.forEach((a) => { pro[a.name] = a.pos; });
const pdist = (x, y) => B._vecNorm(B._vecSub(pro[x], pro[y]));
[['N', 'CA', 1.458], ['CA', 'CB', 1.521], ['CB', 'CG', 1.52], ['CG', 'CD', 1.52], ['CD', 'N', 1.46]].forEach(([x, y, want]) => {
  const d = pdist(x, y);
  ok(Math.abs(d - want) < 0.01, `proline ring bond ${x}-${y} = ${d.toFixed(3)} A (wanted ${want})`);
});
// the 1,3 contacts of a five-membered ring are ~2.4 A — never a bond
const ringContacts = [['N', 'CB'], ['N', 'CG'], ['CA', 'CG'], ['CA', 'CD'], ['CB', 'CD']];
const tight = ringContacts.filter(([x, y]) => pdist(x, y) < 2.2);
ok(tight.length === 0, 'every 1,3 contact of the proline ring is > 2.2 A ('
  + ringContacts.map(([x, y]) => `${x}…${y} ${pdist(x, y).toFixed(2)}`).join(', ') + ')');
const angle = (a, b, c) => {
  const u = B._vecNormalize(B._vecSub(pro[a], pro[b]));
  const v = B._vecNormalize(B._vecSub(pro[c], pro[b]));
  return Math.acos(Math.max(-1, Math.min(1, B._vecDot(u, v)))) * 180 / Math.PI;
};
// the ring angle at CA is the backbone's own (111.2°); the other four are the ring's
const ringAngles = [angle('CD', 'N', 'CA'), angle('CG', 'CD', 'N'), angle('CB', 'CG', 'CD'), angle('CA', 'CB', 'CG')];
const strained = ringAngles.filter((deg) => deg < 100 || deg > 118);
ok(strained.length === 0, 'every ring angle of the proline is an sp3 angle ('
  + ringAngles.map((d) => d.toFixed(1) + '°').join(', ') + ')');
// and the CD protons hang tetrahedrally on CD — outside the C–H window of CA/CB
const hToBackbone = ['HD2', 'HD3'].map((h) => (pro[h] ? Math.min(
  B._vecNorm(B._vecSub(pro[h], pro.CA)), B._vecNorm(B._vecSub(pro[h], pro.CB))) : 0));
ok(hToBackbone.every((d) => d > 1.5), 'the two CD protons stay out of the bond window of CA/CB ('
  + hToBackbone.map((d) => d.toFixed(2)).join(', ') + ' A)');


// ---- 3. the ring closure chooses its side deterministically --------------------
const vd = (p, q) => B._vecNorm(B._vecSub(p, q));
const avoid = B._vecScale(B._vecAdd(pro.CA, pro.CB), 0.5);
const cd = B._ringClose(pro.CG, pro.N, 1.52, 1.46, avoid);
ok(Math.abs(vd(cd, pro.CG) - 1.52) < 1e-9 && Math.abs(vd(cd, pro.N) - 1.46) < 1e-9,
  'the returned CD keeps 1.52 A to CG and 1.46 A to N');
// the OTHER solution of the same circle–circle intersection is the point mirrored
// through the CG–N axis: the two must be on opposite sides of the backbone
const axisD = vd(pro.N, pro.CG);
const axisU = B._vecNormalize(B._vecSub(pro.N, pro.CG));
const axisA = (1.52 * 1.52 - 1.46 * 1.46 + axisD * axisD) / (2 * axisD);
const axisMid = B._vecAdd(pro.CG, B._vecScale(axisU, axisA));
const mirror = B._vecSub(B._vecScale(axisMid, 2), cd);
ok(vd(cd, avoid) > vd(mirror, avoid) + 0.5, 'the returned side is the one AWAY from the CA/CB midpoint ('
  + vd(cd, avoid).toFixed(2) + ' A vs ' + vd(mirror, avoid).toFixed(2) + ' A for its mirror)');
// …and the two points the OLD helper enumerated (±perp, with perp built FROM avoid)
// are EXACTLY equidistant from `avoid`: the tie-break that made the side random.
const oldRingClose = (prev, anchor, lenPrev, lenAnchor, avoidPt) => {
  const d = B._vecNorm(B._vecSub(anchor, prev));
  const u = B._vecNormalize(B._vecSub(anchor, prev));
  const a = (lenPrev * lenPrev - lenAnchor * lenAnchor + d * d) / (2 * d);
  const h = Math.sqrt(Math.max(1e-6, lenPrev * lenPrev - a * a));
  const mid = B._vecAdd(prev, B._vecScale(u, a));
  let perp = B._vecCross(u, B._vecNormalize(B._vecSub(avoidPt, prev)));
  if (B._vecNorm(perp) < 1e-6) perp = B._vecCross(u, [0, 0, 1]);
  perp = B._vecNormalize(perp);
  const c1 = B._vecAdd(mid, B._vecScale(perp, h));
  const c2 = B._vecSub(mid, B._vecScale(perp, h));
  return B._vecNorm(B._vecSub(c1, avoidPt)) > B._vecNorm(B._vecSub(c2, avoidPt)) ? c1 : c2;
};
const oldCd = oldRingClose(pro.CG, pro.N, 1.52, 1.46, avoid);
const oldToCa = vd(oldCd, pro.CA);
const oldToCb = vd(oldCd, pro.CB);
ok(Math.min(oldToCa, oldToCb) < 1.9,
  'the OLD helper returned a CD inside the C–C covalent window — the reported bonds (CD-CA '
  + oldToCa.toFixed(2) + ' A, CD-CB ' + oldToCb.toFixed(2) + ' A)');

// ---- 4. the rule: no three-membered ring in a protein residue ------------------
// The graph NGL really builds for the reported case: the proline residue of the
// generated model, its OWN CONECT bonds plus the two the distance pass invents.
const proNames = ['N', 'CA', 'CB', 'CG', 'CD', 'HD2', 'HD3'];
const proModel = proNames.map((nm) => atomOf(nm, proSeq));
ok(proModel.every(Boolean), 'the proline residue of the model carries N, CA, CB, CG, CD and its two HD');
const proAtoms = proModel.map((a) => ({
  element: a.element, resname: a.resName, residueIndex: a.resSeq, x: a.x, y: a.y, z: a.z, name: a.name,
}));
const localOf = new Map(proModel.map((a, k) => [a.index, k]));
const norm = (s, t) => Math.min(localOf.get(s), localOf.get(t)) * 10 + Math.max(localOf.get(s), localOf.get(t));
const realRing = [];
model.conect.forEach((list, s) => list.forEach((t) => {
  const i = model.bySerial.get(s);
  const j = model.bySerial.get(t);
  if (!i || !j || !localOf.has(i.index) || !localOf.has(j.index)) return;
  const key = norm(i.index, j.index);
  if (!realRing.includes(key)) realRing.push(key);
}));
const ringPairs = realRing.map((key) => [Math.floor(key / 10), key % 10]);
const invented = [[localOf.get(atomOf('CA', proSeq).index), localOf.get(atomOf('CD', proSeq).index)],
  [localOf.get(atomOf('CB', proSeq).index), localOf.get(atomOf('CD', proSeq).index)]];   // CD-CA / CD-CB
const proBonds = [...ringPairs, ...invented];
const bad = impossibleProteinBondIndices(proAtoms, proBonds);
ok(bad.length === 2 && bad[0] === ringPairs.length && bad[1] === ringPairs.length + 1,
  'the rule drops the two invented CD bonds and keeps every real one (' + bad.join(', ') + ')');
const keptPro = keepOnlyCovalentProteinBonds(proAtoms, proBonds);
ok(keptPro.length === ringPairs.length, 'the proline keeps its ' + ringPairs.length + ' real bonds');
const pairName = (k) => proAtoms[proBonds[k][0]].name + '-' + proAtoms[proBonds[k][1]].name;
ok(keptPro.map(pairName).includes('N-CD') && keptPro.map(pairName).includes('CG-CD') && keptPro.map(pairName).includes('N-CA'),
  'the ring stays closed through CG (kept: ' + keptPro.map(pairName).join(' ') + ')');
// the same fragment WITHOUT coordinates still loses exactly two bonds, and the graph
// it leaves behind has no triangle at all
const flatAtoms = proAtoms.map(({ element, resname, residueIndex }) => ({ element, resname, residueIndex }));
const flatKept = keepOnlyCovalentProteinBonds(flatAtoms, proBonds);
ok(flatKept.length === ringPairs.length
  && impossibleProteinBondIndices(flatAtoms, flatKept.map((k) => proBonds[k])).length === 0,
  'without coordinates the rule still leaves a triangle-free graph of ' + flatKept.length + ' bonds');
// a well-built proline (what the builder now produces) has no triangle at all
ok(keepOnlyCovalentProteinBonds(proAtoms, ringPairs).length === ringPairs.length,
  'a correct proline ring is left untouched');

// a LIGAND is not a protein: its three-membered rings (an epoxide, a cyclopropane)
// are real bonds and must survive
const ligAtoms = [
  { element: 'C', resname: 'LIG', residueIndex: 1 },
  { element: 'C', resname: 'LIG', residueIndex: 1 },
  { element: 'C', resname: 'LIG', residueIndex: 1 },
  { element: 'O', resname: 'HOH', residueIndex: 2 },
];
const ligBonds = [[0, 1], [1, 2], [2, 0], [2, 3]];
ok(impossibleProteinBondIndices(ligAtoms, ligBonds).length === 0,
  'a cyclopropane of a ligand keeps all its bonds');
// …and a 1,3 pair ACROSS two residues is not this rule's business either
const crossAtoms = [
  { element: 'C', resname: 'ALA', residueIndex: 0 },    // 0 C of residue 0
  { element: 'C', resname: 'ALA', residueIndex: 0 },    // 1 CA of residue 0
  { element: 'N', resname: 'ALA', residueIndex: 1 },    // 2 N of residue 1
];
ok(impossibleProteinBondIndices(crossAtoms, [[0, 1], [0, 2], [1, 2]]).length === 0,
  'the peptide bond (1,3 through nothing) is never mistaken for a triangle');

// the builder's OWN graph passes the rule untouched — the proof that no legitimate
// protein bond is a triangle
const atomsForRule = model.atoms.map((a) => ({ element: a.element, resname: a.resName, residueIndex: a.resSeq, x: a.x, y: a.y, z: a.z }));
const bondsForRule = [];
// every CONECT line names ONE pair (the builder writes CONECT <serial> <serial>)
model.conect.forEach((list, s) => list.forEach((t) => {
  const i = model.bySerial.get(s);
  const j = model.bySerial.get(t);
  if (i && j) bondsForRule.push([i.index, j.index]);
}));
ok(bondsForRule.length > 300, 'the built model declares ' + bondsForRule.length + ' bonds');
ok(impossibleProteinBondIndices(atomsForRule, bondsForRule).length === 0,
  'the rule removes NOTHING from the builder\'s own graph');
ok(isProteinResidue('pro') && isProteinResidue('HSD') && !isProteinResidue('LIG') && !isProteinResidue(''),
  'the standard residue list includes the variants and excludes a ligand');

// ---- 5. the applier compacts a structure's bond store (mimicked — no GL context) --
const fakeStructure = (atoms, bonds) => ({
  atomCount: atoms.length,
  bondStore: {
    count: bonds.length,
    atomIndex1: Uint32Array.from(bonds.map((b) => b[0])),
    atomIndex2: Uint32Array.from(bonds.map((b) => b[1])),
    bondOrder: Uint8Array.from(bonds.map(() => 1)),
  },
  getAtomProxy() {
    if (!this._proxy) {
      const a = atoms;
      this._proxy = {
        index: 0,
        get element() { return a[this.index].element; },
        get resname() { return a[this.index].resname; },
        get residueIndex() { return a[this.index].residueIndex; },
        get atomname() { return a[this.index].name || a[this.index].element; },
        get x() { return a[this.index].x; },
        get y() { return a[this.index].y; },
        get z() { return a[this.index].z; },
      };
    }
    return this._proxy;
  },
});
const st = fakeStructure(proAtoms, proBonds);
const dropped = enforceCovalentProteinBonds(st);
const left = [];
for (let i = 0; i < st.bondStore.count; i++) left.push(st.bondStore.atomIndex1[i] + '-' + st.bondStore.atomIndex2[i]);
ok(dropped === 2 && st.bondStore.count === realRing.length,
  'applier drops the 2 impossible bonds (dropped=' + dropped + ', left=' + st.bondStore.count + ')');
ok(!left.includes('1-4') && !left.includes('2-4'), 'applier surviving graph: ' + left.join(' '));
ok(enforceCovalentProteinBonds(st) === 0, 'applier is idempotent');
ok(enforceCovalentProteinBonds(null) === 0, 'applier tolerates a missing structure');
ok(enforceCovalentProteinBonds({ bondStore: { count: 0 } }) === 0, 'applier tolerates a structure with no bonds');

// ---- 6. the viewer applies the rule before anything reads the graph -------------
const viewer = readFileSync('src/components/NMRMoleculeViewer.jsx', 'utf8');
ok(/import \{[^}]*enforceCovalentProteinBonds[^}]*\} from '\.\.\/utils\/proteinBondRule'/.test(viewer),
  'viewer imports the rule');
const applied = viewer.split('enforceCovalentProteinBonds(').length - 1;
ok(applied >= 3, 'viewer applies it on every load path (' + applied + ' call sites)');
// Les trois endroits sont les TROIS portes d’entrée d’une structure : la
// principale, une chaîne / une molécule découpée (loadChainMolecule) et une
// molécule ajoutée — fichier, code PDB ou URL, qui passent tous par
// registerExtraComponent depuis que leurs molécules sont exposées une par une.
const extraFn = viewer.indexOf('const registerExtraComponent = useCallback');
const extraRule = viewer.indexOf('enforceCovalentProteinBonds(comp)', extraFn);
const extraParts = viewer.indexOf('const parts = splitStructureIntoMolecules(comp);', extraFn);
ok(extraFn > 0 && extraRule > extraFn && extraParts > extraRule,
  '…et une molécule AJOUTÉE est prunée AVANT que ses molécules soient exposées');
const mainLoad = viewer.indexOf("component = await stage.loadFile(blob, { ext: loadRequest.ext || 'pdb' });");
const mainCall = viewer.indexOf('enforceCovalentProteinBonds(component)');
const firstRep = viewer.indexOf('applyCurrentStyleTo(component', mainLoad);
ok(mainCall > mainLoad && (firstRep === -1 || mainCall < firstRep),
  'the main load prunes the graph BEFORE the first representation is built');

console.log(failures === 0 ? '\nPASS' : '\nFAIL (' + failures + ')');
process.exit(failures === 0 ? 0 : 1);
