/* =========================================================================
   _viewer_molecule_choice_test.mjs — CHOISIR, COCHER ET PLACER UNE MOLÉCULE
   dans la fenêtre de styling du viewer 3D.

   Les rapports de cette session, mot pour mot :

     • « the "all" or "none" buttons should select or deselect the ticks of each
       molecule and it is not what they do. » — ☑ All / ☐ None n'écrivaient que
       `visibleMolKeys` (la molécule ENTIÈRE) alors que les ✔ que l'on VOIT dans la
       barre sont ceux des SECTIONS : les deux états sont maintenant écrits ensemble ;
     • « there is no way to select a molecule so I cannot try the "fit to chosen"
       button. » — chaque espace a son bouton 🎯 (le choix SE VOIT : espace violet
       « chosen »), et le cadre des sections suit la MOLÉCULE — il comparait
       `selectedMolKey` à l'identifiant d'une SECTION (`main::protein`) et ne pouvait
       donc JAMAIS s'allumer ;
     • « move and rotate button need to be inside each molecule » PUIS « The separated
       move and rotate buttons are impractical, it would be better to simply continue
       to move and rotate with the mouse, the only difference is that one molecule is
       moved and the other stay fixed. » — les boutons ✥ Move · ↻ Rotate et le « mode »
       qu'ils armaient ont donc disparu : un glisser qui COMMENCE sur une molécule la
       tourne (gauche) ou la fait glisser (droit), les autres ne bougent pas, et la
       molécule qu'une main attrape devient la référence ★ (voir §3) ;
     • « keep the selection generated by "selections and pymol" window in all
       instances of one experiment » — gardé par _pymol_selections_test.mjs.

   Le viewer est un .jsx : ce garde-fou lit la SOURCE (les gestes sont des fermetures
   du composant, elles ne s'extraient pas), comme les autres garde-fous du fichier.
   ========================================================================= */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

let passed = 0;
const VIEW = readFileSync(new URL('./src/components/NMRMoleculeViewer.jsx', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const has = (needle, what) => {
  assert.ok(VIEW.includes(needle), `${what}\n  introuvable : ${needle}`);
  passed += 1;
};
const gone = (needle, what) => {
  assert.ok(!VIEW.includes(needle), `${what}\n  encore présent : ${needle}`);
  passed += 1;
};
const countOf = (re) => (VIEW.match(re) || []).length;

/* ── 1. LE ✔ D'UNE MOLÉCULE, ET LE BOUTON ☑ ALL / ☐ NONE QUI LE COCHE ────── */
has('const molShown = (key) => visibleMolKeys.has(key);', 'le tick d’une molécule est UNE fonction');
has('const setMolShown = (key, on) => {', '…avec SON geste (un seul endroit écrit visibleMolKeys)');
has('const setEverySectionTick = (on) => {', '☑/☐ écrit AUSSI les ✔ des sections');
has('  setEverySectionTick(on);', '…et c’est ce que ☑ All / ☐ None appelle');
has('  const on = !(keys.length && keys.every((k) => visibleMolKeys.has(k)));',
  'le bouton lit l’état RÉEL avant de décider « all » ou « none »');
has('  bumpSectionEpoch();', '…et la scène est reconstruite (le ✔ des sections change ce qui est dessiné)');
has('<input type="checkbox" checked={molShown(molKey)} onChange={() => setMolShown(molKey, !molShown(molKey))}',
  'chaque espace de molécule PORTE son ✔');
has('the tick of THIS molecule (☑ All / ☐ None tick them all at once)',
  '…et son titre dit que ☑ All les coche tous');
// Les deux états sont bien distincts : la molécule entière ET ses sections.
has('const [visibleMolKeys, setVisibleMolKeys] = useState(() => new Set([\'main\']));',
  'l’état « la molécule est montrée » existe toujours (il est ce que l’effet de visibilité lit)');
has('const [sectionVis, setSectionVis] = useState({});', '…et les ✔ de sections ont le leur');

/* ── 2. LE CHOIX DE LA MOLÉCULE (la référence de « 🎯 Fit to chosen ») ───── */
has('const chooseMol = (key) => {', 'choisir une molécule est UN geste, nommé');
has('onClick={() => chooseMol(molKey)}', '…et chaque espace a son bouton ★');
has("★ {chosen ? 'main' : 'set main'}",
  '…qui DIT « main » — la référence — au lieu d’un « chosen » discret (le rapport de cette session : « You say that the main is the molecule to move but there is no way to define the main. »)');
has('★ main: {molNameOf(selectedMolKey)}',
  'la barre NOMME en permanence la molécule de référence (on ne peut plus se demander laquelle c’est)');
has('★ main: {molNameOf(selectedMolKey)} · a drag on a molecule turns/slides it',
  '…et la ligne dit à QUOI elle sert : le geste de la souris ET le fit');
has('🖱 drag a molecule: turn · right-drag: slide',
  'les deux boutons de §2 sont remplacés par UNE pastille qui dit le geste (le rapport : « The separated move and rotate buttons are impractical »)');
gone("const [mouseMode, setMouseMode] = useState('off');",
  '…le mode à armer a disparu : le geste est la souris, il n’y a plus rien à sélectionner avant de placer');
has('Drag ON a molecule to turn it about its own centre (left button)',
  '…et la pastille dit le geste entier (gauche = tourner, droit = glisser, fond · Alt = caméra)');
has('const chosen = selectedMolKey === molKey;', '…et l’espace choisi porte un cadre violet');
has("${chosen ? 'border-violet-400 bg-violet-50/60' : 'border-slate-300 bg-slate-50/70'}",
  '…le cadre de l’espace suit le choix');
has('Superpose every SHOWN structure onto the CHOSEN one',
  'le titre de 🎯 Fit to chosen dit qui est la référence (l’espace violet)');
gone('${selectedMolKey === sec.id',
  'le cadre d’une SECTION ne compare plus une molécule à un identifiant de section (jamais vrai)');
has("const molKeyOfSection = String(sec.id).split('::')[0];",
  '…il lit la MOLÉCULE de la section (le préfixe avant « :: »)');
has("${selectedMolKey === molKeyOfSection ? 'border-violet-400' : 'border-slate-200'}",
  '…donc les rangées de la molécule choisie le montrent');

/* ── 3. LE GESTE DE LA SOURIS — UNE MOLÉCULE BOUGE, LES AUTRES NON ────────── */
has('const installMoleculeDrag = (stage) => {',
  'UN installateur de geste, nommé (le rapport : « simply continue to move and rotate with the mouse »)');
has("stage.mouseControls.remove('drag-left');", 'les deux glissers « nus » de NGL sont remplacés par les nôtres');
has("stage.mouseControls.add('drag-left', dragRotate);", '…un glisser sur une molécule la TOURNE');
has("stage.mouseControls.add('drag-right', dragSlide);", '…un glisser droit sur une molécule la FAIT GLISSER');
has("stage.mouseControls.add('drag-alt-left', cameraRotate);", '…et Alt+gauche rend la caméra, même sur une molécule');
has('if (st.transformComponent) tb.rotateComponent(dx, dy);',
  'le geste est celui de NGL : la composante s’il y en a une sous le curseur');
has('else tb.rotate(dx, dy);', '…sinon la caméra (le fond reste le tourne-disque)');
has('if (st.transformComponent) tb.panComponent(dx, dy);', '…et pareil pour le glisser (droit)');
has('const compToGrab = (e) => {', 'la molécule est choisie AU PIXEL DE L’APPUI (le picking de NGL, synchrone)');
has('stage.transformComponent = g ? g.comp : undefined;',
  '…et `transformComponent` est remis à zéro quand le fond est touché (sinon le geste suivant déplacerait la molécule précédente)');
has('if (g) setSelectedMolKey(g.key);', 'la molécule attrapée DEVIENT la référence ★ (🎯 Fit, ↺ et la ligne ★ la suivent)');
has('if (e.ctrlKey || e.metaKey || e.altKey || e.shiftKey) return;',
  'Ctrl · Méta · Alt · Maj laissent le geste à NGL (Ctrl+Maj = ses propres gestes de composante)');
has("stage.mouseControls.preset('default');", '…et tout est rendu à NGL quand la scène s’en va');
gone('setMouseMode(', 'aucun bouton de mode ne subsiste');
gone('const dragMoveOnDown = (e) => {', 'ni le calque plein cadre qui suspendait la caméra');

console.log(`_viewer_molecule_choice_test.mjs — ${passed} assertions OK (✔ des molécules · choix 🎯 · Move/Rotate par molécule)`);
