/* =========================================================================
   _viewer_molecule_choice_test.mjs — CHOISIR, COCHER ET PLACER UNE MOLÉCULE
   dans la fenêtre de styling du viewer 3D.

   Les rapports de cette session, mot pour mot :

     • « the "all" or "none" buttons should select or deselect the ticks of each
       molecule and it is not what they do. » — ☑ All / ☐ None n'écrivaient que
       `visibleMolKeys` (la molécule ENTIÈRE) alors que les ✔ que l'on VOIT dans la
       barre sont ceux des SECTIONS : les deux états sont maintenant écrits ensemble ;
     • « there is no way to select a molecule so I cannot try the "fit to chosen"
       button. » — chaque espace a son bouton 🎯 (le choix SE VOIT : espace violet
       « chosen »), et le cadre des sections suit la MOLÉCULE — il comparait
       `selectedMolKey` à l'identifiant d'une SECTION (`main::protein`) et ne pouvait
       donc JAMAIS s'allumer ;
     • « move and rotate button need to be inside each molecule » — les deux boutons
       ✥ Move · ↻ Rotate d'un espace SÉLECTIONNENT cette molécule avant d'armer le
       geste, et chaque espace porte son ✔ ;
     • « keep the selection generated by "selections and pymol" window in all
       instances of one experiment » — gardé par _pymol_selections_test.mjs.

   Le viewer est un .jsx : ce garde-fou lit la SOURCE (les gestes sont des fermetures
   du composant, elles ne s'extraient pas), comme les autres garde-fous du fichier.
   ========================================================================= */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

let passed = 0;
const VIEW = readFileSync(new URL('./src/components/NMRMoleculeViewer.jsx', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const has = (needle, what) => {
  assert.ok(VIEW.includes(needle), `${what}\n  introuvable : ${needle}`);
  passed += 1;
};
const gone = (needle, what) => {
  assert.ok(!VIEW.includes(needle), `${what}\n  encore présent : ${needle}`);
  passed += 1;
};
const countOf = (re) => (VIEW.match(re) || []).length;

/* ── 1. LE ✔ D'UNE MOLÉCULE, ET LE BOUTON ☑ ALL / ☐ NONE QUI LE COCHE ────── */
has('const molShown = (key) => visibleMolKeys.has(key);', 'le tick d’une molécule est UNE fonction');
has('const setMolShown = (key, on) => {', '…avec SON geste (un seul endroit écrit visibleMolKeys)');
has('const setEverySectionTick = (on) => {', '☑/☐ écrit AUSSI les ✔ des sections');
has('  setEverySectionTick(on);', '…et c’est ce que ☑ All / ☐ None appelle');
has('  const on = !(keys.length && keys.every((k) => visibleMolKeys.has(k)));',
  'le bouton lit l’état RÉEL avant de décider « all » ou « none »');
has('  bumpSectionEpoch();', '…et la scène est reconstruite (le ✔ des sections change ce qui est dessiné)');
has('<input type="checkbox" checked={molShown(molKey)} onChange={() => setMolShown(molKey, !molShown(molKey))}',
  'chaque espace de molécule PORTE son ✔');
has('the tick of THIS molecule (☑ All / ☐ None tick them all at once)',
  '…et son titre dit que ☑ All les coche tous');
// Les deux états sont bien distincts : la molécule entière ET ses sections.
has('const [visibleMolKeys, setVisibleMolKeys] = useState(() => new Set([\'main\']));',
  'l’état « la molécule est montrée » existe toujours (il est ce que l’effet de visibilité lit)');
has('const [sectionVis, setSectionVis] = useState({});', '…et les ✔ de sections ont le leur');

/* ── 2. LE CHOIX DE LA MOLÉCULE (la référence de « 🎯 Fit to chosen ») ───── */
has('const chooseMol = (key) => {', 'choisir une molécule est UN geste, nommé');
has('onClick={() => chooseMol(molKey)}', '…et chaque espace a son bouton ★');
has("★ {chosen ? 'main' : 'set main'}",
  '…qui DIT « main » — la référence — au lieu d’un « chosen » discret (le rapport de cette session : « You say that the main is the molecule to move but there is no way to define the main. »)');
has('★ main: {molNameOf(selectedMolKey)}',
  'la barre NOMME en permanence la molécule de référence (on ne peut plus se demander laquelle c’est)');
has("★ main: {molNameOf(selectedMolKey)} · 🎯 Fit to chosen and §2's ✥ Move · ↻ Rotate act on it",
  '…et la ligne dit à QUOI elle sert : le fit ET les deux gestes de §2');
has("✥ Move{mouseMode === 'move' ? ' ●' : ''}: {molNameOf(selectedMolKey)}",
  'les boutons ✥ Move de §2 nomment LAQUELLE ils déplacent (leur titre le répétait, leur étiquette le montre)');
has("↻ Rotate{mouseMode === 'rotate' ? ' ●' : ''}: {molNameOf(selectedMolKey)}", '…idem pour ↻ Rotate');
has('Drag to move « ${molNameOf(selectedMolKey)} »', 'le calque de la souris dit quelle molécule suit le geste');
has('const chosen = selectedMolKey === molKey;', '…et l’espace choisi porte un cadre violet');
has("${chosen ? 'border-violet-400 bg-violet-50/60' : 'border-slate-300 bg-slate-50/70'}",
  '…le cadre de l’espace suit le choix');
has('Superpose every SHOWN structure onto the CHOSEN one',
  'le titre de 🎯 Fit to chosen dit qui est la référence (l’espace violet)');
gone('${selectedMolKey === sec.id',
  'le cadre d’une SECTION ne compare plus une molécule à un identifiant de section (jamais vrai)');
has("const molKeyOfSection = String(sec.id).split('::')[0];",
  '…il lit la MOLÉCULE de la section (le préfixe avant « :: »)');
has("${selectedMolKey === molKeyOfSection ? 'border-violet-400' : 'border-slate-200'}",
  '…donc les rangées de la molécule choisie le montrent');

/* ── 3. MOVE · ROTATE DANS CHAQUE MOLÉCULE ───────────────────────────────── */
has("onClick={() => { setSelectedMolKey(molKey); setMouseMode((m) => (m === 'move' ? 'off' : 'move')); }}",
  '✥ Move d’un espace SÉLECTIONNE sa molécule avant d’armer le geste');
has("onClick={() => { setSelectedMolKey(molKey); setMouseMode((m) => (m === 'rotate' ? 'off' : 'rotate')); }}",
  '…et ↻ Rotate aussi');
has("const dragMoveComp = () => (selectedMolKey === 'main'", 'le geste n’agit QUE sur la molécule choisie');
has('const dragMoveOnDown = (e) => {', '…par un seul point d’entrée (le calque de la souris)');
// Chaque espace a bien ses DEUX boutons, et une seule fois par espace.
const moveButtons = countOf(/setMouseMode\(\(m\) => \(m === 'move' \? 'off' : 'move'\)\)/g);
const rotateButtons = countOf(/setMouseMode\(\(m\) => \(m === 'rotate' \? 'off' : 'rotate'\)\)/g);
assert.equal(moveButtons, 2, 'le Move existe à DEUX endroits : l’espace de la molécule et §2 Modify');
assert.equal(rotateButtons, 2, '…idem pour le Rotate');
passed += 2;

console.log(`_viewer_molecule_choice_test.mjs — ${passed} assertions OK (✔ des molécules · choix 🎯 · Move/Rotate par molécule)`);
