/* ============================================================================
   FIGURE ANNOTATIONS — arrows and drop shadows for the Image Builder canvas.

   Two things the composition needed and had no model for:

     1. ARROWS. A publication figure very often needs a pointer — “this peak”,
        “compare with panel B”, “the substrate goes in here”. The builder only
        knew PANELS (an `objects[]` entry = a letter + a grid cell + a figure),
        so an arrow had nowhere to live. Arrows are therefore their own
        canvas-level list, in millimetres on the same space as the SVG viewBox:
        they take no letter, occupy no cell and never disturb the panel
        numbering. The three shapes asked for come from two independent
        switches — `style` (straight | curved) and `double` (one head | heads
        at BOTH ends) — so “curved, double-ended” works like the plain cases.

     2. DROP SHADOWS. Panels and arrows can each cast a shadow, stored as one
        little record `{ dx, dy, blur, color, opacity }` (mm) that is rendered
        by ONE SVG `<feDropShadow>` filter — so the shadow is part of the
        composition itself and every export (Export PNG, Save canvas, Insert
        into project) keeps it: those paths rasterize this very SVG.

   Everything here is PURE (no React, no DOM) and is imported by BOTH
   src/components/ImageBuilder.jsx and the scratch test _builder_arrows_test.mjs,
   so the geometry that is verified is exactly the geometry that is drawn.
   ========================================================================= */

/** Defaults of a NEW, freshly switched-on shadow (mm; opacity 0…1). */
export const DEFAULT_SHADOW = { dx: 1.5, dy: 1.5, blur: 1.2, color: '#0f172a', opacity: 0.35 };

/** Accepted ranges of the shadow controls — anything stored is clamped to them. */
export const SHADOW_LIMITS = { dx: [-40, 40], dy: [-40, 40], blur: [0, 12], opacity: [0.02, 1] };

const num = (v, fallback) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
};
const clamp = (v, [lo, hi], fallback) => Math.max(lo, Math.min(hi, num(v, fallback)));
const r3 = (v) => Math.round(Number(v) * 1000) / 1000;

/* ── SHADOW ──────────────────────────────────────────────────────────────── */

/**
 * The usable drop shadow of an element, or NULL when it has none.
 * A shadow is “on” as soon as the record exists (the UI writes `null` to switch
 * it off), and every field is filled from DEFAULT_SHADOW / clamped, so a record
 * typed by hand — or written by an older version — can never produce a filter
 * with a NaN offset (which would silently drop the whole element).
 */
export const shadowSpec = (shadow) => {
  if (!shadow) return null;
  return {
    dx: clamp(shadow.dx, SHADOW_LIMITS.dx, DEFAULT_SHADOW.dx),
    dy: clamp(shadow.dy, SHADOW_LIMITS.dy, DEFAULT_SHADOW.dy),
    blur: clamp(shadow.blur, SHADOW_LIMITS.blur, DEFAULT_SHADOW.blur),
    opacity: clamp(shadow.opacity, SHADOW_LIMITS.opacity, DEFAULT_SHADOW.opacity),
    color: (typeof shadow.color === 'string' && shadow.color.trim()) ? shadow.color.trim() : DEFAULT_SHADOW.color
  };
};

/**
 * Id of the `<filter>` of one shadowed element. Element ids are generated by
 * the builder (`obj_…`, `arr_…`) but a loaded canvas is not to be trusted, so
 * anything that could break an id reference (`#`, spaces…) is replaced.
 */
export const shadowFilterId = (key) => `fshadow-${String(key == null ? '' : key).replace(/[^\w-]/g, '_')}`;

/* ── ARROWS ──────────────────────────────────────────────────────────────── */

/** Defaults of a NEW arrow: a short straight red arrow with one head. */
export const DEFAULT_ARROW = {
  style: 'straight',   // 'straight' | 'curved'
  double: false,       // true → heads at BOTH ends
  curve: 8,            // bulge of the curved shape (mm, signed; + = right of the direction)
  color: '#dc2626',
  width: 0.7,          // stroke width of the shaft (mm)
  headSize: 3,         // length of one head (mm)
  dash: false,
  shadow: null         // { dx, dy, blur, color, opacity } — see shadowSpec
};

/** The shaft stops this fraction of a head short of the tip (the head covers it). */
export const ARROW_HEAD_TRIM = 0.8;
/** Half-width of a head = headSize × this (a slender, publication-looking head). */
export const ARROW_HEAD_HALF = 0.42;

/** A brand-new arrow. `patch` overrides the defaults (ends, colour…). */
export const newArrow = (id, patch = {}) => ({
  id: String(id == null ? '' : id),
  x1: 0, y1: 0, x2: 0, y2: 0,
  ...DEFAULT_ARROW,
  ...patch
});

/**
 * A stored arrow with every field filled and usable. A canvas saved before
 * arrows existed, a hand-edited record or a `null` in the list all end up as a
 * drawable arrow instead of crashing the renderer.
 */
export const normalizeArrow = (a) => {
  const src = a || {};
  return {
    ...DEFAULT_ARROW,
    ...src,
    style: src.style === 'curved' ? 'curved' : 'straight',
    double: !!src.double,
    dash: !!src.dash,
    curve: num(src.curve, DEFAULT_ARROW.curve),
    width: Math.max(0.05, num(src.width, DEFAULT_ARROW.width)),
    headSize: Math.max(0.2, num(src.headSize, DEFAULT_ARROW.headSize)),
    x1: num(src.x1, 0), y1: num(src.y1, 0), x2: num(src.x2, 0), y2: num(src.y2, 0)
  };
};

/** Point of a quadratic Bézier: B(t) = (1−t)²P0 + 2(1−t)t C + t²P2. */
export const quadPoint = (p0, pc, p2, t) => {
  const u = 1 - t;
  return {
    x: u * u * p0.x + 2 * u * t * pc.x + t * t * p2.x,
    y: u * u * p0.y + 2 * u * t * pc.y + t * t * p2.y
  };
};

/** Length of the control polygon — an upper bound of the curve, used as mm→t ruler. */
export const quadLength = (p0, pc, p2) =>
  Math.hypot(pc.x - p0.x, pc.y - p0.y) + Math.hypot(p2.x - pc.x, p2.y - pc.y);

/**
 * The control point of a CURVED arrow. The user types the BULGE they see in mm
 * (`curve`), and a quadratic Bézier only reaches HALF way to its control point
 * (B(0.5) = M/2 + C/2), so the control sits at TWICE the bulge — that is what
 * makes the number in the properties panel the distance between the chord and
 * the curve. A positive bulge goes to the right of the direction of travel.
 */
export const arrowControl = (a) => {
  const n = normalizeArrow(a);
  const dx = n.x2 - n.x1, dy = n.y2 - n.y1;
  const len = Math.hypot(dx, dy);
  const mx = (n.x1 + n.x2) / 2, my = (n.y1 + n.y2) / 2;
  if (!(len > 0)) return { x: mx, y: my };
  return { x: mx - (dy / len) * 2 * n.curve, y: my + (dx / len) * 2 * n.curve };
};

const unit = (x, y, fallback) => {
  const len = Math.hypot(x, y);
  if (!(len > 0)) return fallback;
  // `|| 0` also turns the -0 a plain negation produces into 0: a direction of
  // (-1, -0) is the same direction as (-1, 0), and the strict comparison the
  // tests (and any consumer) do would not see it that way.
  return { x: x / len || 0, y: y / len || 0 };
};

/**
 * EVERYTHING the canvas needs to draw one arrow, from a single source:
 *   path     — the shaft as SVG path data, already stopped short of each head
 *   heads    — [{ tip, dir }] (one head, or two when `double`; `dir` points
 *              OUTWARD, so a head is always drawn at the very end it belongs to)
 *   p0 / p2  — the two ends in mm (the drag handles sit exactly there)
 *   arrow    — the normalized record (colour, width, dash, head size…)
 *   straight / curved / control / chord — what the properties panel reports
 * A `straight` arrow is a LINE from end to end; a `curved` one is a quadratic
 * whose bulge is `curve` mm. Zero-length arrows (the two ends typed on top of
 * each other) stay drawable: shaft from end to end, no head.
 */
export const arrowGeometry = (raw) => {
  const arrow = normalizeArrow(raw);
  const p0 = { x: arrow.x1, y: arrow.y1 };
  const p2 = { x: arrow.x2, y: arrow.y2 };
  const chordX = p2.x - p0.x, chordY = p2.y - p0.y;
  const chord = Math.hypot(chordX, chordY);
  const curved = arrow.style === 'curved' && Math.abs(arrow.curve) > 0.01 && chord > 0;
  const pc = arrowControl(arrow);

  if (!(chord > 0)) {
    return {
      arrow, straight: !curved, curved, p0, pc, p2, chord: 0, control: pc,
      startDir: { x: -1, y: 0 }, endDir: { x: 1, y: 0 },
      shaft: { from: p0, to: p2 },
      path: `M ${r3(p0.x)} ${r3(p0.y)} L ${r3(p2.x)} ${r3(p2.y)}`,
      heads: []
    };
  }

  const at = (t) => (curved ? quadPoint(p0, pc, p2, t) : { x: p0.x + chordX * t, y: p0.y + chordY * t });
  const total = curved ? quadLength(p0, pc, p2) : chord;
  const headStart = !!arrow.double;
  const headEnd = true;                              // an arrow always points somewhere
  const trim = arrow.headSize * ARROW_HEAD_TRIM;
  let dStart = headStart ? Math.min(trim, total * 0.4) : 0;
  let dEnd = headEnd ? Math.min(trim, total * 0.4) : 0;
  // Never let the two trims cross: on a very short double arrow the heads then
  // simply meet in the middle instead of the shaft flipping direction.
  const over = dStart + dEnd - total;
  if (over > 0) { const half = over / 2; dStart = Math.max(0, dStart - half); dEnd = Math.max(0, dEnd - half); }
  const from = at(total > 0 ? dStart / total : 0);
  const to = at(total > 0 ? 1 - dEnd / total : 1);

  // Outward direction at each end: the tangent of the curve at that end (for a
  // straight arrow, the direction of the line itself).
  const endDir = curved ? unit(p2.x - pc.x, p2.y - pc.y, { x: 1, y: 0 }) : unit(chordX, chordY, { x: 1, y: 0 });
  const startDir = curved
    ? unit(p0.x - pc.x, p0.y - pc.y, { x: -1, y: 0 })
    : unit(-chordX, -chordY, { x: -1, y: 0 });

  const heads = [];
  if (headStart) heads.push({ tip: { x: p0.x, y: p0.y }, dir: startDir });
  if (headEnd) heads.push({ tip: { x: p2.x, y: p2.y }, dir: endDir });

  const path = curved
    ? `M ${r3(from.x)} ${r3(from.y)} Q ${r3(pc.x)} ${r3(pc.y)} ${r3(to.x)} ${r3(to.y)}`
    : `M ${r3(from.x)} ${r3(from.y)} L ${r3(to.x)} ${r3(to.y)}`;

  return { arrow, straight: !curved, curved, p0, pc, p2, chord, control: pc, startDir, endDir, shaft: { from, to }, path, heads };
};

/** The shaft of an arrow as SVG path data (see arrowGeometry). */
export const arrowPathData = (a) => arrowGeometry(a).path;

/** The head(s) of an arrow: [{ tip, dir }] — one head, or two when `double`. */
export const arrowHeads = (a) => arrowGeometry(a).heads;

/**
 * The filled triangle of ONE head: the tip sits exactly on the end of the
 * arrow (so the arrow points where the user aimed it), the base is `size`
 * behind it along `dir`, and the head is `ARROW_HEAD_HALF × size` wide.
 */
export const arrowHeadPath = (tip, dir, size) => {
  const len = Math.max(0.1, num(size, DEFAULT_ARROW.headSize));
  const d = unit(dir && dir.x, dir && dir.y, { x: 1, y: 0 });
  const bx = tip.x - d.x * len, by = tip.y - d.y * len;
  const px = -d.y, py = d.x;              // perpendicular of the direction
  const w = len * ARROW_HEAD_HALF;
  return `M ${r3(tip.x)} ${r3(tip.y)} L ${r3(bx + px * w)} ${r3(by + py * w)} L ${r3(bx - px * w)} ${r3(by - py * w)} Z`;
};
