/* =========================================================================
   src/utils/hydrogenBondRule.js
   A hydrogen has ONE heavy neighbour — never two.

   La demande : « In the autogenerated structure of proteins there are bonds which
   should never be there: HD2-CE, HD3-CE, HD2-NE, HD3-NE, HG3-CD, HG2-CD, HB2-CG,
   HB3-CG. Never draw them in proteins. »

   A hydrogen carries a single bond: one heavy atom. The pairs above are not bonds
   but CLASHES — a CH2 proton sitting 1.24 to 1.28 Å from the NEXT heavy atom of
   its own side chain (0.73 Å from the ring nitrogen of a proline) — and NGL binds
   every H–heavy pair inside the covalent window of `AtomProxy.connectedTo`
   (covalent radii + 0.3 Å, i.e. 0.57 – 1.37 Å for H–C; read in
   node_modules/ngl/dist/ngl.js.map → src/proxy/atom-proxy.ts), so its distance
   pass drew them ON TOP of the file's own CONECT records: the PDB parser's default
   `inferBonds:'all'` adds bonds in addition to the explicit ones.

   The generated structures no longer produce such a clash (the builder places every
   methylene proton tetrahedrally to BOTH its heavy neighbours — see the
   placeSidechainAtoms post-pass of NMRSections.jsx, mirrored in
   rebuildProteinHydrogens.js). This module makes the drawing unconditional: in
   ANY protein, a hydrogen keeps one heavy bond — the shortest — and every extra
   "bond" is removed from the graph before a single representation reads it.
   ========================================================================= */

/** Covalent radii in Å — the same table the lipid classifier uses. */
const COVALENT_RADII = {
  H: 0.31, D: 0.31, B: 0.84, C: 0.76, N: 0.71, O: 0.66, F: 0.57,
  P: 1.07, S: 1.05, CL: 1.02, SE: 1.16, BR: 1.20, I: 1.39,
};

/** Element of an atom, from NGL's element field or the leading letter of its name. */
export const hydrogenElementOf = (name, element) => {
  const e = String(element || '').replace(/[^A-Za-z]/g, '').toUpperCase();
  if (e) return e;
  const m = /[A-Za-z]/.exec(String(name || ''));
  return m ? m[0].toUpperCase() : '';
};

/** The longest distance a bond between two elements can have (covalent radii + 0.3,
 *  the margin NGL itself uses in AtomProxy.connectedTo). */
export const hydrogenBondLimit = (e1, e2) => (COVALENT_RADII[e1] || 0.77)
  + (COVALENT_RADII[e2] || 0.77) + 0.3;

/**
 * Which bonds survive the rule "a hydrogen has one heavy neighbour".
 *
 * @param {Array<{element:string,x:number,y:number,z:number}>} atoms by atom index
 * @param {Array<[number, number, number?]>} bonds atom-index pairs (+ bond order)
 * @returns {number[]} the indices of `bonds` to keep, ascending
 */
export const keepOnlyOneHeavyBondPerHydrogen = (atoms, bonds) => {
  const list = bonds || [];
  const isH = (i) => {
    const a = atoms && atoms[i];
    return !!a && (a.element === 'H' || a.element === 'D');
  };
  const heavyBondsOf = new Map();     // hydrogen index -> [{ k, d2 }]
  list.forEach((bond, k) => {
    const i = bond && bond[0];
    const j = bond && bond[1];
    const iH = isH(i);
    const jH = isH(j);
    if (iH === jH) return;            // heavy–heavy (or H–H): not this rule's business
    const h = iH ? i : j;
    const other = iH ? j : i;
    const a = atoms[h];
    const b = atoms[other];
    if (!a || !b) return;
    const d2 = (a.x - b.x) ** 2 + (a.y - b.y) ** 2 + (a.z - b.z) ** 2;
    if (!heavyBondsOf.has(h)) heavyBondsOf.set(h, []);
    heavyBondsOf.get(h).push({ k, d2 });
  });
  const dropped = new Set();
  heavyBondsOf.forEach((found) => {
    if (found.length < 2) return;     // the ordinary case: one heavy bond
    found.slice().sort((p, q) => p.d2 - q.d2 || p.k - q.k).slice(1)
      .forEach((e) => dropped.add(e.k));
  });
  const keep = [];
  list.forEach((_, k) => { if (!dropped.has(k)) keep.push(k); });
  return keep;
};

/**
 * Apply the rule to a loaded NGL component (or structure) BEFORE any representation
 * reads the bond graph — the same place `ensureGlycanBonds` writes its linkages.
 * The bond store is compacted in place: it is a flat array of index pairs, so
 * dropping the impossible entries and lowering its count is the whole edit (the
 * app already pokes that store when it adds a glycosidic bond).
 *
 * @returns {number} how many impossible bonds were removed
 */
export const enforceOneHeavyBondPerHydrogen = (componentOrStructure) => {
  const structure = componentOrStructure && componentOrStructure.structure
    ? componentOrStructure.structure
    : componentOrStructure;
  if (!structure || !structure.bondStore) return 0;
  const store = structure.bondStore;
  const bondCount = store.count || 0;
  const atomCount = structure.atomCount || 0;
  if (!bondCount || !atomCount || typeof structure.getAtomProxy !== 'function') return 0;

  const ap = structure.getAtomProxy();
  const atoms = [];
  for (let i = 0; i < atomCount; i++) {
    ap.index = i;
    atoms.push({ element: hydrogenElementOf(ap.atomname, ap.element), x: ap.x, y: ap.y, z: ap.z });
  }
  const bonds = [];
  for (let k = 0; k < bondCount; k++) {
    bonds.push([store.atomIndex1[k], store.atomIndex2[k], store.bondOrder ? store.bondOrder[k] : 1]);
  }

  const keep = keepOnlyOneHeavyBondPerHydrogen(atoms, bonds);
  if (keep.length === bondCount) return 0;   // nothing impossible in this structure

  let w = 0;
  keep.forEach((k) => {
    store.atomIndex1[w] = bonds[k][0];
    store.atomIndex2[w] = bonds[k][1];
    if (store.bondOrder) store.bondOrder[w] = bonds[k][2];
    w++;
  });
  store.count = w;
  try { structure.bondCount = w; } catch { /* the store itself is what a reader sees */ }
  return bondCount - w;
};
