/* =========================================================================
   src/utils/proteinBondRule.js
   Two heavy atoms of a protein residue never share a heavy neighbour.

   La demande : « In the autogenerated structure of proteins there are bonds which
   should never be there: CD-CA, CD-CB. Never draw them in proteins. »

   No amino acid contains a three-membered ring: every covalent bond of a residue
   either joins two atoms of DIFFERENT rings, or is part of a ring of five or six
   (Pro, His, Phe, Trp, Tyr), or of no ring at all. So when two heavy atoms of the
   same standard residue are BOTH bonded to a third, that pair cannot be covalently
   bonded — the bond would close a triangle, which does not exist in a protein.

   Where the reported "CD-CA / CD-CB" came from: the proline ring closure
   (_ringClose in NMRSections.jsx) picked its side with a comparison that was always
   a tie, so on some geometries CD was placed 1.59 Å from CA and 1.77 Å from CB —
   inside the covalent window of AtomProxy.connectedTo (radii + 0.3 Å = 1.82 Å for a
   C–C pair). The PDB parser's default `inferBonds:'all'` ADDS a bond for every pair
   inside that window, on top of the file's own CONECT records, so the viewer drew
   the two impossible bars and the ring looked closed twice.

   The builder geometry is fixed (the proline ring now closes on a near-regular
   pentagon — see _protein_heavy_bonds_test.mjs), and this module makes the drawing
   unconditional: in ANY protein, the bonds that close a three-membered ring are
   removed from the graph before a single representation reads it, whatever the file
   (or a mis-built model) said. Only the SMALLEST set of bonds needed is dropped, so
   the residue keeps its real rings — on the reported proline, exactly the two
   invented bars go and the five-membered ring stays closed.

   A residue the module does not recognise (a ligand, a sugar, a modified residue
   outside the standard set) is left EXACTLY as the file declares it: a cyclopropane
   or an epoxide in a ligand is a real three-membered ring and must be drawn.
   ========================================================================= */

/** The 20 standard amino acids plus the protonation / oxidation / selenium variants
 *  the app already knows elsewhere (rebuildProteinHydrogens, AA_1_TO_3). */
export const PROTEIN_RESIDUES = new Set([
  'ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLN', 'GLU', 'GLY', 'HIS', 'ILE',
  'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP', 'TYR', 'VAL',
  // HIS tautomers / charge states, oxidised and seleno variants, and the two
  // extra genetically encoded residues.
  'HSD', 'HSE', 'HSP', 'HID', 'HIE', 'HIP', 'CYX', 'CYM', 'CSO', 'CME', 'SEC', 'MSE', 'PYL',
]);

/** A standard residue name? (case-insensitive, tolerant of a missing name) */
export const isProteinResidue = (name) => PROTEIN_RESIDUES.has(String(name || '').trim().toUpperCase());

/** A heavy atom (everything but a hydrogen / deuterium)? */
const isHeavy = (element) => {
  const e = String(element || '').trim().toUpperCase();
  return !!e && e !== 'H' && e !== 'D';
};


/**
 * Which bonds of a protein graph are impossible: the smallest set of heavy–heavy
 * bonds of standard residues that leaves the graph without a three-membered ring.
 *
 * A bond that closes a triangle is not drawn, but neither is its whole ring: the
 * deletion is a MINIMUM cover — the bond guilty of the most triangles goes first,
 * and, between two equally guilty ones, the LONGEST (a distance-inferred bond is
 * always the 1,3 contact of a ring — CA…CD at 2.1 Å, CB…CD at 2.2 Å in the report —
 * so it is longer than the bonds that carry it). On the reported proline that
 * removes exactly the two invented bonds and leaves the five-membered ring closed.
 *
 * @param {Array<{element:string,resname?:string,residueIndex?:number,x?:number,y?:number,z?:number}>} atoms by atom index
 * @param {Array<[number, number, number?]>} bonds atom-index pairs (+ bond order)
 * @returns {number[]} the indices of `bonds` that must not be drawn, ascending
 */
export const impossibleProteinBondIndices = (atoms, bonds) => {
  const list = bonds || [];
  const isStandard = (index) => {
    const a = atoms && atoms[index];
    return !!a && isHeavy(a.element) && isProteinResidue(a.resname);
  };
  // The heavy bonds of every standard residue, with their length when the caller
  // passed the coordinates (a structure always has them).
  const byResidue = new Map();
  list.forEach((bond, k) => {
    const i = bond && bond[0];
    const j = bond && bond[1];
    if (i === undefined || j === undefined) return;
    const a = atoms && atoms[i];
    const b = atoms && atoms[j];
    if (!a || !b) return;
    if (!isHeavy(a.element) || !isHeavy(b.element)) return;   // a hydrogen is hydrogenBondRule's business
    if (a.residueIndex === undefined || a.residueIndex !== b.residueIndex) return;   // same residue only
    if (!isStandard(i) || !isStandard(j)) return;             // a ligand keeps its rings
    const len = [a, b].every((x) => Number.isFinite(x.x) && Number.isFinite(x.y) && Number.isFinite(x.z))
      ? Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z)
      : null;
    if (!byResidue.has(a.residueIndex)) byResidue.set(a.residueIndex, []);
    byResidue.get(a.residueIndex).push({ k, i, j, len });
  });

  const out = [];
  byResidue.forEach((edges) => {
    const alive = new Map(edges.map((e) => [e.k, e]));
    for (;;) {
      // neighbours of every atom, read from the bonds STILL STANDING
      const nb = new Map();
      alive.forEach(({ i, j }) => {
        if (!nb.has(i)) nb.set(i, new Set());
        if (!nb.has(j)) nb.set(j, new Set());
        nb.get(i).add(j);
        nb.get(j).add(i);
      });
      let victim = null;
      alive.forEach((e) => {
        let closed = 0;
        nb.get(e.i).forEach((c) => {
          if (c === e.j) return;
          if (!isHeavy(atoms[c] && atoms[c].element)) return;
          if (nb.get(e.j).has(c)) closed++;
        });
        if (!closed) return;
        if (!victim || closed > victim.closed
          || (closed === victim.closed && (e.len || 0) > (victim.e.len || 0))) victim = { e, closed };
      });
      if (!victim) break;               // the residue's graph is triangle-free
      alive.delete(victim.e.k);
      out.push(victim.e.k);
    }
  });
  return out.sort((a, b) => a - b);
};

/**
 * Which bonds survive the rule "no three-membered ring in a protein residue".
 *
 * @param {Array<{element:string,resname?:string,residueIndex?:number}>} atoms by atom index
 * @param {Array<[number, number, number?]>} bonds atom-index pairs (+ bond order)
 * @returns {number[]} the indices of `bonds` to keep, ascending
 */
export const keepOnlyCovalentProteinBonds = (atoms, bonds) => {
  const list = bonds || [];
  const dropped = new Set(impossibleProteinBondIndices(atoms, list));
  const keep = [];
  list.forEach((_, k) => { if (!dropped.has(k)) keep.push(k); });
  return keep;
};

/**
 * Apply the rule to a loaded NGL component (or structure) BEFORE any representation
 * reads the bond graph — the same place `ensureGlycanBonds` writes its linkages and
 * `enforceOneHeavyBondPerHydrogen` prunes the hydrogen bonds. The bond store is
 * compacted in place: it is a flat array of index pairs, so dropping the impossible
 * entries and lowering its count is the whole edit (the app already pokes that store
 * when it adds a glycosidic bond).
 *
 * @returns {number} how many impossible bonds were removed
 */
export const enforceCovalentProteinBonds = (componentOrStructure) => {
  const structure = componentOrStructure && componentOrStructure.structure
    ? componentOrStructure.structure
    : componentOrStructure;
  if (!structure || !structure.bondStore) return 0;
  const store = structure.bondStore;
  const bondCount = store.count || 0;
  const atomCount = structure.atomCount || 0;
  if (!bondCount || !atomCount || typeof structure.getAtomProxy !== 'function') return 0;

  const ap = structure.getAtomProxy();
  const atoms = [];
  for (let i = 0; i < atomCount; i++) {
    ap.index = i;
    atoms.push({
      element: String(ap.element || '').trim(),
      resname: String(ap.resname || ''),
      residueIndex: ap.residueIndex,
      x: ap.x, y: ap.y, z: ap.z,          // the length tie-break reads them
    });
  }
  const bonds = [];
  for (let k = 0; k < bondCount; k++) {
    bonds.push([store.atomIndex1[k], store.atomIndex2[k], store.bondOrder ? store.bondOrder[k] : 1]);
  }

  const keep = keepOnlyCovalentProteinBonds(atoms, bonds);
  if (keep.length === bondCount) return 0;   // nothing impossible in this structure

  let w = 0;
  keep.forEach((k) => {
    store.atomIndex1[w] = bonds[k][0];
    store.atomIndex2[w] = bonds[k][1];
    if (store.bondOrder) store.bondOrder[w] = bonds[k][2];
    w++;
  });
  store.count = w;
  try { structure.bondCount = w; } catch { /* the store itself is what a reader sees */ }
  return bondCount - w;
};
