/* =========================================================================
src/utils/viewerRayShadows.js
CAST SHADOWS for the « ✨ Ray » still.

THE METHOD, AND WHY IT CHANGED (the report: « the shadows generated by ray are
ugly, they dirty the molecule, and the aromatic rings do not project their
hexagons on the surrounding ribbons »).

The first version rebuilt an APPROXIMATION of the scene out of the atoms (a
ball per atom, a capsule per bond, and — for a band — a brush of small balls
re-derived from the geometry's sections) and multiplied the result into every
pixel of the still. Measured against NGL 2.4 in a real browser (Chrome,
SwiftShader), three of its premises were simply false:

  1. THE BAND WAS NEVER READ. NGL's cartoon geometry is an INDEXED TRIANGLE
     MESH — `position` is 3 floats per vertex (2430 floats for 810 vertices)
     with a `normal` attribute and a 4728-index Uint16Array. The old reader
     assumed a stride of 12 floats per vertex, so `2430 % 12 !== 0` made
     `bandSectionsOf` return null: a CARTOON CAST NOTHING AT ALL (only the
     atoms' balls did), which is the « flat, detached smudge » of the reports.
     On a ribbon (936 floats — a multiple of 12 by accident) the reader mixed
     up position / dir / size at the wrong stride and built a brush pointing in
     a made-up direction: the ugly blobs.

  2. THE AROMATIC PLATES WERE INVISIBLE. The filled hexagons of « Stylized
     rings » are `MeshBuffer`s handed to the component with
     `addBufferRepresentation`; they live in `comp.reprList` with
     `rep.type === 'buffer'` and NO `structureView`. The old reader only looked
     at representation TYPES it knew (`FLAT_STROKE_BY_TYPE.cartoon` /
     `.ribbon`), so a base's hexagon was neither an occluder nor a receiver:
     no hexagon could ever land on the ribbon behind it.

  3. THE COMPOSITE DIRTIED EVERYTHING. `applyShadowToPixels` multiplied every
     pixel where the mask was > 0.002 — background included — and the mask was
     inflated twice: the receiver's OWN footprint was added to the PCF disc of
     every pixel (so each stroke self-shadowed along its edges), and a wide
     « ambient » blur of the mask was blended in at 0.85 over a 4 Å radius (so
     a dark smear spread over the molecule and past its silhouette). Nothing
     knew the surface's normal, so a face turned AWAY from the lamp was
     darkened by the same amount as a lit one.

THE METHOD NOW. Nothing is rebuilt and nothing is guessed: the same geometry
NGL draws is rasterized here, twice, in the two frames that matter.

  · THE OCCLUDERS AND THE RECEIVERS are the DRAWN SHAPES, in three kinds:
      — a SPHERE per atom and a CAPSULE per bond, ANALYTIC (NGL draws those as
        screen-space impostors — verified: their buffers carry `radius`,
        `position1`/`position2` and NO normal — so a sphere/capsule of the
        given radius IS the drawn shape, per pixel, exactly);
      — the REAL TRIANGLES of every buffer that carries a `normal` attribute:
        cartoon · ribbon · tube · rope · surface · and the RING PLATES (the
        hexagons), which is what makes an aromatic ring project its hexagon.
        The frame of the stills is read from the geometry itself, never from a
        table of representation types: a buffer with normals is a surface, a
        buffer without them is an impostor (balls, sticks, lines).
  · TWO PASSES: the camera's (it stores, per pixel, the WORLD POINT of the
    visible surface and its WORLD NORMAL — no depth is needed to compare, the
    point itself is the truth) and the lamp's (the same shapes, orthographic,
    keeping the NDC depth of those same surface points).
  · THE TEST is the honest one: the receiver's own world point is projected
    into the lamp and compared with what the lamp saw FIRST at that pixel. The
    receiver is in its own depth map, so it occludes itself by exactly zero —
    no footprint trick, no bias keeping a fake self-shadow alive.
  · THE DARKNESS IS THE LAMP'S SHARE. A pixel is darkened by
    `1 − strength · occlusion · w(normal)`, where `w` falls with the angle
    between the surface and the lamp (a face the lamp does not light has no
    light to remove) and never goes below `facingFloor` so the shadow stays
    legible on a ribbon's side walls. The mask is ZERO outside the receiver's
    own coverage, so the background — and every pixel the molecule does not
    own — is never touched. That is what stops the « dirt ».

WHAT A SHADOW CANNOT DO IN NGL 2.4. The interactive canvas has NO shadow pass at
all (verified in the installed build: no shadow map, no SSAO — only an unused
three.js AO-map chunk that nothing binds), so a ✨ Ray still is the ONLY place a
cast shadow can exist in this viewer. It is computed here and multiplied into the
pixels NGL has just written, after the fact: the scene itself is never touched.

======================================================================== */
export const RAY_SHADOW_MAX_PIXELS = 20e6;
export const RAY_SHADOW_DEFAULTS = Object.freeze({
  strength: 0.55,
  softness: 1.6,
  maskMaxWidth: 1400,
  bias: 0.35,
  sphereScale: 1,
  maxAtoms: 300000,
  maxTriangles: 400000,
  fitMargin: 1.06,
  pcfTaps: 8,
  penumbra: 1.5,
  penumbraMax: 8,
  blur: 1,
  /* THE LIGHT'S SHARE, AT THE LIMIT. `w = floor + (1 − floor)·max(0, N·L)`,
     `floor` being this value: a surface whose normal is perpendicular to the
     lamp keeps this much of the shadow. 0 would be physical (there is no light
     there to remove) and would make a shadow vanish on the side walls of a
     ribbon — exactly where the eye looks for it. 1 would darken a face the
     lamp never lights: the old « dirt ». */
  facingFloor: 0.35,
});
export const SHADOW_TAPS_PER_PIXEL = 2.5;
export const SHADOW_MAX_TAPS = 64;
export const SHADOW_BLUR_REF = 20;
export const SHADOW_BLUR_MIN = 0.25;
export const SHADOW_BLUR_STROKE_FRACTION = 0.6;
export const INVISIBLE_OPACITY = 0.02;
export const PROXY_STROKE_BY_TYPE = Object.freeze({
  sphere: { kind: 'vdw', min: 0.12 },
  spacefill: { kind: 'vdw', min: 0.12 },
  surface: { kind: 'vdw', min: 0.12 },
  'ball+stick': { kind: 'ball', core: 0.15, aspect: 2, min: 0.2 },
  ballstick: { kind: 'ball', core: 0.15, aspect: 2, min: 0.2 },
  hyperball: { kind: 'ball', core: 0.15, aspect: 2, min: 0.2 },
  licorice: { kind: 'bond', core: 0.25, min: 0.2 },
  base: { kind: 'bond', core: 0.3, min: 0.2 },
  backbone: { kind: 'bond', core: 0.15, min: 0.2 },
  line: { kind: 'hair', min: 0.15 },
  wireframe: { kind: 'hair', min: 0.15 },
  cartoon: { kind: 'spline', base: 0.45, scale: 0.7, min: 0.3 },
  ribbon: { kind: 'spline', base: 0.45, scale: 4, min: 0.3 },
  tube: { kind: 'tube', base: 0.5, min: 0.2 },
  rope: { kind: 'spline', base: 0.3, scale: 1, min: 0.2 },
  trace: { kind: 'spline', base: 0.35, scale: 1, min: 0.2 },
});
export const LINKED_KINDS = Object.freeze({ spline: 1, tube: 1, bond: 1, ball: 1 });
export const BACKBONE_ONLY_KINDS = Object.freeze({ spline: 1, tube: 1 });
/* ⚠ THE IMPOSTORS. NGL draws a ball, a stick, a wire or a point as ONE
   screen-space quad per primitive whose shape the FRAGMENT SHADER cuts out of
   `radius` / `position1` / `position2`; there is no surface at all in their
   vertex data (measured: no `normal` attribute, six indices per primitive — a
   quad). Their true shape is the analytic sphere / capsule of their radius,
   which is what this module rasterizes, so their buffers must NEVER be read as
   triangles: a quad is not a molecule. */
export const IMPOSTOR_TYPES = Object.freeze({
  sphere: 1, spacefill: 1, 'ball+stick': 1, ballstick: 1, hyperball: 1,
  licorice: 1, line: 1, wireframe: 1, point: 1, backbone: 1, base: 1, trace: 1,
});
const LINK_MAX = 4.2;

// ============================================================================
// 1. MATH UTILITIES
// ============================================================================
export const sub3 = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
export const cross3 = (a, b) => [
  a[1] * b[2] - a[2] * b[1],
  a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0],
];
export const dot3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
export const length3 = (a) => Math.sqrt(dot3(a, a));
export const normalize3 = (a) => {
  const l = length3(a);
  return l > 1e-9 ? [a[0] / l, a[1] / l, a[2] / l] : [0, 0, 1];
};
export const mat4Multiply = (a, b, out = new Array(16)) => {
  for (let c = 0; c < 4; c += 1) {
    for (let r = 0; r < 4; r += 1) {
      out[c * 4 + r] = a[r] * b[c * 4]
        + a[4 + r] * b[c * 4 + 1]
        + a[8 + r] * b[c * 4 + 2]
        + a[12 + r] * b[c * 4 + 3];
    }
  }
  return out;
};
export const mat4TransformPoint = (m, p, out = new Array(4)) => {
  out[0] = m[0] * p[0] + m[4] * p[1] + m[8] * p[2] + m[12];
  out[1] = m[1] * p[0] + m[5] * p[1] + m[9] * p[2] + m[13];
  out[2] = m[2] * p[0] + m[6] * p[1] + m[10] * p[2] + m[14];
  out[3] = m[3] * p[0] + m[7] * p[1] + m[11] * p[2] + m[15];
  return out;
};
export const clipToScreen = (clip, width, height, out = new Array(3)) => {
  if (!(Math.abs(clip[3]) > 1e-9)) return null;
  const x = clip[0] / clip[3];
  const y = clip[1] / clip[3];
  const z = clip[2] / clip[3];
  if (!(z >= -1.001 && z <= 1.001)) return null;
  out[0] = (x * 0.5 + 0.5) * width;
  out[1] = (0.5 - y * 0.5) * height;
  out[2] = z;
  return out;
};
export const viewAxesOf = (view) => ({
  right: [view[0], view[4], view[8]],
  up: [view[1], view[5], view[9]],
  back: [view[2], view[6], view[10]],
});
export const mat4Identity = () => [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
export const mat4LookAt = (eye, target, up) => {
  const zAxis = normalize3(sub3(eye, target));
  const xAxis = normalize3(cross3(up, zAxis));
  const yAxis = cross3(zAxis, xAxis);
  return [
    xAxis[0], yAxis[0], zAxis[0], 0,
    xAxis[1], yAxis[1], zAxis[1], 0,
    xAxis[2], yAxis[2], zAxis[2], 0,
    -dot3(xAxis, eye), -dot3(yAxis, eye), -dot3(zAxis, eye), 1,
  ];
};
export const mat4Orthographic = (left, right, bottom, top, near, far) => [
  2 / (right - left), 0, 0, 0,
  0, 2 / (top - bottom), 0, 0,
  0, 0, -2 / (far - near), 0,
  -(right + left) / (right - left),
  -(top + bottom) / (top - bottom),
  -(far + near) / (far - near),
  1,
];
export const boundsOf = (positions, count) => {
  const n = Math.max(0, Math.min(count || positions.length / 3, positions.length / 3));
  if (!n) return { center: [0, 0, 0], radius: 1 };
  let minX = Infinity, minY = Infinity, minZ = Infinity;
  let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
  for (let i = 0; i < n; i += 1) {
    const x = positions[i * 3], y = positions[i * 3 + 1], z = positions[i * 3 + 2];
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
    if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
  }
  const center = [(minX + maxX) / 2, (minY + maxY) / 2, (minZ + maxZ) / 2];
  const radius = Math.max(1e-3, 0.5 * Math.sqrt((maxX - minX) ** 2 + (maxY - minY) ** 2 + (maxZ - minZ) ** 2));
  return { center, radius };
};
export const boundsBoxOf = (positions, count) => {
  const n = Math.max(0, Math.min(count || positions.length / 3, positions.length / 3));
  if (!n) return { min: [-1, -1, -1], max: [1, 1, 1] };
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < n; i += 1) {
    for (let c = 0; c < 3; c += 1) {
      const v = positions[i * 3 + c];
      if (!Number.isFinite(v)) continue;
      if (v < min[c]) min[c] = v;
      if (v > max[c]) max[c] = v;
    }
  }
  for (let c = 0; c < 3; c += 1) {
    if (!Number.isFinite(min[c]) || !Number.isFinite(max[c])) { min[c] = -1; max[c] = 1; }
  }
  return { min, max };
};
export const unionBoxOf = (a, b) => {
  if (!a || !a.min || !a.max) return b && b.min && b.max ? b : { min: [-1, -1, -1], max: [1, 1, 1] };
  if (!b || !b.min || !b.max) return a;
  return {
    min: [Math.min(a.min[0], b.min[0]), Math.min(a.min[1], b.min[1]), Math.min(a.min[2], b.min[2])],
    max: [Math.max(a.max[0], b.max[0]), Math.max(a.max[1], b.max[1]), Math.max(a.max[2], b.max[2])],
  };
};
/* ⚠ THE FRAME MUST HOLD WHAT THE SHAPES *OCCUPY*, NOT WHERE THEIR CENTRES ARE.
   A ball is a SOLID: its surface reaches `radius` beyond its centre, and the
   lamp's frustum is fitted to this box (shadowRigOf). Fitted to the centres, the
   near hemisphere of every atom sitting at the edge of the box fell OUTSIDE the
   frustum — and an occluder the lamp never rasterized is a shadow that vanishes
   without a word (the « no cast shadow » of the report, in the corner of every
   scene). The box is therefore widened by the largest drawn stroke. */
export const expandBoxOf = (box, margin = 0) => {
  const m = Math.max(0, Number(margin) || 0);
  if (!box || !box.min || !box.max) return { min: [-m, -m, -m], max: [m, m, m] };
  return {
    min: [box.min[0] - m, box.min[1] - m, box.min[2] - m],
    max: [box.max[0] + m, box.max[1] + m, box.max[2] + m],
  };
};
export const boxCornersOf = ({ min, max } = {}, out = []) => {
  const lo = min || [-1, -1, -1];
  const hi = max || [1, 1, 1];
  for (let i = 0; i < 8; i += 1) {
    if (!out[i]) out[i] = [0, 0, 0];
    out[i][0] = i & 1 ? hi[0] : lo[0];
    out[i][1] = i & 2 ? hi[1] : lo[1];
    out[i][2] = i & 4 ? hi[2] : lo[2];
  }
  return out;
};

// ============================================================================
// 2. RASTERIZATION & SHADOW TESTING
// ============================================================================
/* ⚠ THE DEPTH IS THE SURFACE'S, NEVER A CENTRE'S. The first version projected
   the CENTRE of every sphere and wrote that one depth over the whole disc: a
   billboard. Half of a ball then sat « behind » its own centre, so a ball
   occluded its own far edge, and the pixel's world point — which is what the
   lamp is asked about — was the middle of the atom instead of the patch of skin
   the camera really sees. Every rasterizer below writes the true point and its
   true normal, so the two passes can be compared honestly. */
export const ndcZOf = (clip, x, y, z) => {
  const cw = clip[3] * x + clip[7] * y + clip[11] * z + clip[15];
  if (!(Math.abs(cw) > 1e-9)) return 2;
  return (clip[2] * x + clip[6] * y + clip[10] * z + clip[14]) / cw;
};
const writePixel = (out, idx, z, x, y, z2, nx, ny, nz2, scale, needN) => {
  if (!(z < out.depth[idx])) return false;
  out.depth[idx] = z;
  out.hit[idx] = 1;
  if (out.world) {
    out.world[idx * 3] = x;
    out.world[idx * 3 + 1] = y;
    out.world[idx * 3 + 2] = z2;
  }
  if (needN && out.normal) {
    const l = Math.sqrt(nx * nx + ny * ny + nz2 * nz2);
    const s = l > 1e-9 ? 1 / l : 0;
    out.normal[idx * 3] = nx * s;
    out.normal[idx * 3 + 1] = ny * s;
    out.normal[idx * 3 + 2] = nz2 * s;
  }
  return true;
};
/* THE BUFFERS OF ONE PASS, ALLOCATED ONCE AND THEN SHARED. A single pass is
   built by SEVERAL rasterizers that all draw into the SAME depth map — the balls
   first, then the capsules that fill the links between them, then the REAL
   TRIANGLES (a band, a plate) — each of them keeping whatever is nearer. They are
   therefore initialised WHEN THEY ARE ALLOCATED and never cleared again: wiping
   them here would erase the balls the moment the capsules arrived.
   ⚠ The buffers must also live ON `out`, which is what `writePixel` reads: the
   first version built them locally and only published `world` / `normal`, so a
   fresh pass had `out.depth === undefined` and every ball threw on the very first
   writePixel. */
const surfaceBuffer = (out, w, h, needWorld = true, needNormal = true) => {
  const size = w * h;
  if (!out.depth || out.depth.length !== size) {
    out.depth = new Float32Array(size);
    out.depth.fill(2);
    out.hit = new Uint8Array(size);
    out.hit.fill(0);
  }
  if (needWorld && (!out.world || out.world.length !== size * 3)) out.world = new Float32Array(size * 3);
  if (needNormal && (!out.normal || out.normal.length !== size * 3)) out.normal = new Float32Array(size * 3);
  return out;
};
export const rasterizeSpheres = ({
  positions, radii, count = 0, clip, width, height,
  radiusScale = 1, right = [1, 0, 0], up = [0, 1, 0], back = [0, 0, 1],
  needNormal = true, needWorld = true,
}, out = {}) => {
  const w = Math.max(1, Math.round(width));
  const h = Math.max(1, Math.round(height));
  const n = Math.max(0, Math.min(count || Math.floor(positions.length / 3), Math.floor(positions.length / 3)));
  surfaceBuffer(out, w, h, needWorld, needNormal);
  const clipPt = new Array(4);
  const scr = new Array(3);
  const scrEdge = new Array(3);
  const maxRadius = Math.max(w, h) * 2;

  for (let i = 0; i < n; i += 1) {
    const x = positions[i * 3], y = positions[i * 3 + 1], z = positions[i * 3 + 2];
    if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) continue;
    const r = Math.max(0.1, (radii ? radii[i] : 1.7) * radiusScale);
    const c = clipToScreen(mat4TransformPoint(clip, [x, y, z], clipPt), w, h, scr);
    if (!c) continue;
    let rad = 1;
    if (clipToScreen(mat4TransformPoint(clip, [
      x + up[0] * r, y + up[1] * r, z + up[2] * r,
    ], clipPt), w, h, scrEdge)) {
      const dx = scrEdge[0] - c[0], dy = scrEdge[1] - c[1];
      rad = Math.max(1, Math.min(Math.sqrt(dx * dx + dy * dy), maxRadius));
    }
    const cx = c[0], cy = c[1];
    const x0 = Math.max(0, Math.floor(cx - rad));
    const x1 = Math.min(w - 1, Math.ceil(cx + rad));
    const y0 = Math.max(0, Math.floor(cy - rad));
    const y1 = Math.min(h - 1, Math.ceil(cy + rad));
    const r2 = rad * rad;
    /* The image plane's ÅNGSTRÖM PER PIXEL at this atom: a pixel offset turns
       into the point of the sphere it really sees (the parallel-ray
       approximation: ~0.04 Å of error for a 1.7 Å ball seen from 80 Å). */
    const perPx = r / rad;

    for (let py = y0; py <= y1; py += 1) {
      const dy = py + 0.5 - cy;
      const row = py * w;
      for (let px = x0; px <= x1; px += 1) {
        const dx = px + 0.5 - cx;
        const d2 = dx * dx + dy * dy;
        if (d2 > r2) continue;
        const u = dx * perPx;
        const v = dy * perPx;
        const n2 = r * r - u * u - v * v;
        if (!(n2 > 0)) continue;
        const nd = Math.sqrt(n2);
        const wx = x + right[0] * u + up[0] * v + back[0] * nd;
        const wy = y + right[1] * u + up[1] * v + back[1] * nd;
        const wz = z + right[2] * u + up[2] * v + back[2] * nd;
        writePixel(out, row + px, ndcZOf(clip, wx, wy, wz), wx, wy, wz,
          right[0] * u + up[0] * v + back[0] * nd,
          right[1] * u + up[1] * v + back[1] * nd,
          right[2] * u + up[2] * v + back[2] * nd, r, needNormal);
      }
    }
  }
  return { ...out, width: w, height: h, count: n };
};

export const rasterizeCapsules = ({
  positions, radii, edges, clip, width, height,
  radiusScale = 1, right = [1, 0, 0], up = [0, 1, 0], back = [0, 0, 1],
  needNormal = true, needWorld = true,
}, out = {}) => {
  const w = Math.max(1, Math.round(width));
  const h = Math.max(1, Math.round(height));
  surfaceBuffer(out, w, h, needWorld, needNormal);
  if (!out.depth) return out;

  const clipPt = new Array(4);
  const scrA = new Array(3), scrB = new Array(3);
  const edgeA = new Array(3), edgeB = new Array(3);

  for (let i = 0; i + 1 < (edges ? edges.length : 0); i += 2) {
    const iA = edges[i], iB = edges[i + 1];
    const ax = positions[iA * 3], ay = positions[iA * 3 + 1], az = positions[iA * 3 + 2];
    const bx = positions[iB * 3], by = positions[iB * 3 + 1], bz = positions[iB * 3 + 2];

    const cA = clipToScreen(mat4TransformPoint(clip, [ax, ay, az], clipPt), w, h, scrA);
    const cB = clipToScreen(mat4TransformPoint(clip, [bx, by, bz], clipPt), w, h, scrB);
    if (!cA || !cB) continue;

    const rA = Math.max(0.1, radii[iA] * radiusScale);
    const rB = Math.max(0.1, radii[iB] * radiusScale);

    let pxRadA = 1, pxRadB = 1;
    if (clipToScreen(mat4TransformPoint(clip, [ax + up[0] * rA, ay + up[1] * rA, az + up[2] * rA], clipPt), w, h, edgeA)) {
      pxRadA = Math.max(1, Math.sqrt((edgeA[0] - cA[0]) ** 2 + (edgeA[1] - cA[1]) ** 2));
    }
    if (clipToScreen(mat4TransformPoint(clip, [bx + up[0] * rB, by + up[1] * rB, bz + up[2] * rB], clipPt), w, h, edgeB)) {
      pxRadB = Math.max(1, Math.sqrt((edgeB[0] - cB[0]) ** 2 + (edgeB[1] - cB[1]) ** 2));
    }

    const maxR = Math.max(pxRadA, pxRadB);
    const x0 = Math.max(0, Math.floor(Math.min(cA[0], cB[0]) - maxR));
    const x1 = Math.min(w - 1, Math.ceil(Math.max(cA[0], cB[0]) + maxR));
    const y0 = Math.max(0, Math.floor(Math.min(cA[1], cB[1]) - maxR));
    const y1 = Math.min(h - 1, Math.ceil(Math.max(cA[1], cB[1]) + maxR));

    const dx = cB[0] - cA[0];
    const dy = cB[1] - cA[1];
    const len2 = dx * dx + dy * dy;
    const perA = rA / pxRadA;
    const perB = rB / pxRadB;

    for (let py = y0; py <= y1; py += 1) {
      const row = py * w;
      const deltaY = py + 0.5 - cA[1];
      for (let px = x0; px <= x1; px += 1) {
        const deltaX = px + 0.5 - cA[0];
        let t = 0;
        if (len2 > 0) t = Math.max(0, Math.min(1, (deltaX * dx + deltaY * dy) / len2));
        const offX = deltaX - t * dx;
        const offY = deltaY - t * dy;
        const radAtT = pxRadA + t * (pxRadB - pxRadA);
        if (offX * offX + offY * offY > radAtT * radAtT) continue;
        /* THE SURFACE OF THE TUBE, not its axis (same recipe as the sphere,
           with the axis point in place of the centre): a cylinder's radial
           profile is the same at every t, and the round caps come out right
           because t is clamped to the ends. */
        const rr = rA + t * (rB - rA);
        const perPx = perA + t * (perB - perA);
        const u = offX * perPx;
        const v = offY * perPx;
        const n2 = rr * rr - u * u - v * v;
        if (!(n2 > 0)) continue;
        const nd = Math.sqrt(n2);
        const wx = ax + t * (bx - ax) + right[0] * u + up[0] * v + back[0] * nd;
        const wy = ay + t * (by - ay) + right[1] * u + up[1] * v + back[1] * nd;
        const wz = az + t * (bz - az) + right[2] * u + up[2] * v + back[2] * nd;
        writePixel(out, row + px, ndcZOf(clip, wx, wy, wz), wx, wy, wz,
          right[0] * u + up[0] * v + back[0] * nd,
          right[1] * u + up[1] * v + back[1] * nd,
          right[2] * u + up[2] * v + back[2] * nd, rr, needNormal);
      }
    }
  }
  return out;
};

/* ⚠ THE REAL TRIANGLES — the half of the method that was missing. An INDEXED
   mesh (`position` 3 floats per vertex, `normal` 3 floats per vertex, an index
   array of triples) is rasterized here the way the GPU would: the screen-area
   test picks the pixels, the NDC depth (linear in screen space — exact) picks
   the visible one, and the WORLD POINT and the normal are interpolated with the
   PERSPECTIVE-CORRECT weights (a plate seen at an angle must land where it is,
   not where a naive interpolation would put it). This is what makes a ring
   plate hide the ribbon behind it in the shape of its hexagon. */
export const rasterizeTriangles = ({
  positions, normals = null, indices, count = 0, clip, width, height, stride = 1,
  needWorld = true, needNormal = true,
}, out = {}) => {
  const w = Math.max(1, Math.round(width));
  const h = Math.max(1, Math.round(height));
  surfaceBuffer(out, w, h, needWorld, needNormal);
  if (!out.depth) return out;
  const total = Math.max(0, Math.min(
    count || Math.floor(indices.length / 3),
    Math.floor(indices.length / 3),
  ));
  const step = Math.max(1, Math.round(stride));
  const sa = new Array(3), sb = new Array(3), sc = new Array(3);
  const clipPt = new Array(4);
  let drawn = 0;

  for (let t = 0; t < total; t += step) {
    const ia = indices[t * 3] * 3, ib = indices[t * 3 + 1] * 3, ic = indices[t * 3 + 2] * 3;
    const ax = positions[ia], ay = positions[ia + 1], az = positions[ia + 2];
    const bx = positions[ib], by = positions[ib + 1], bz = positions[ib + 2];
    const cx = positions[ic], cy = positions[ic + 1], cz = positions[ic + 2];
    const wa = mat4TransformPoint(clip, [ax, ay, az], clipPt);
    const wA = wa[3];
    const pa = clipToScreen(wa, w, h, sa);
    if (!pa) continue;
    const wb = mat4TransformPoint(clip, [bx, by, bz], clipPt);
    const wB = wb[3];
    const pb = clipToScreen(wb, w, h, sb);
    if (!pb) continue;
    const wc = mat4TransformPoint(clip, [cx, cy, cz], clipPt);
    const wC = wc[3];
    const pc = clipToScreen(wc, w, h, sc);
    if (!pc) continue;

    const area = (pb[0] - pa[0]) * (pc[1] - pa[1]) - (pb[1] - pa[1]) * (pc[0] - pa[0]);
    if (!(Math.abs(area) > 1e-9)) continue;
    const inv = 1 / area;
    const x0 = Math.max(0, Math.floor(Math.min(pa[0], pb[0], pc[0])));
    const x1 = Math.min(w - 1, Math.ceil(Math.max(pa[0], pb[0], pc[0])));
    const y0 = Math.max(0, Math.floor(Math.min(pa[1], pb[1], pc[1])));
    const y1 = Math.min(h - 1, Math.ceil(Math.max(pa[1], pb[1], pc[1])));
    const kA = Math.abs(wA) > 1e-9 ? 1 / wA : 0;
    const kB = Math.abs(wB) > 1e-9 ? 1 / wB : 0;
    const kC = Math.abs(wC) > 1e-9 ? 1 / wC : 0;
    drawn += 1;

    for (let py = y0; py <= y1; py += 1) {
      const row = py * w;
      const y = py + 0.5;
      for (let px = x0; px <= x1; px += 1) {
        const x = px + 0.5;
        const l0 = ((pb[0] - x) * (pc[1] - y) - (pb[1] - y) * (pc[0] - x)) * inv;
        if (l0 < 0) continue;
        const l1 = ((pc[0] - x) * (pa[1] - y) - (pc[1] - y) * (pa[0] - x)) * inv;
        if (l1 < 0) continue;
        const l2 = 1 - l0 - l1;
        if (l2 < 0) continue;
        const idx = row + px;
        const zNdc = l0 * pa[2] + l1 * pb[2] + l2 * pc[2];
        if (!(zNdc < out.depth[idx])) continue;
        const sum = l0 * kA + l1 * kB + l2 * kC;
        const s = Math.abs(sum) > 1e-9 ? 1 / sum : 0;
        const m0 = l0 * kA * s, m1 = l1 * kB * s, m2 = l2 * kC * s;
        const wx = m0 * ax + m1 * bx + m2 * cx;
        const wy = m0 * ay + m1 * by + m2 * cy;
        const wz = m0 * az + m1 * bz + m2 * cz;
        let nx = 0, ny = 0, nz = 1;
        if (normals) {
          nx = m0 * normals[ia] + m1 * normals[ib] + m2 * normals[ic];
          ny = m0 * normals[ia + 1] + m1 * normals[ib + 1] + m2 * normals[ic + 1];
          nz = m0 * normals[ia + 2] + m1 * normals[ib + 2] + m2 * normals[ic + 2];
        }
        writePixel(out, idx, zNdc, wx, wy, wz, nx, ny, nz, 1, needNormal && !!normals);
      }
    }
  }
  return { ...out, triangles: total, drawn };
};

export const softenMask = (mask, width, height, radius) => {
  const w = Math.max(1, Math.round(width));
  const h = Math.max(1, Math.round(height));
  const r = Number(radius) || 0;
  if (!(r > 0)) return mask;
  const far = Math.max(1, Math.round(r));
  const weights = [];
  let sum = 0;
  for (let i = -far; i <= far; i += 1) {
    const k = Math.max(0, 1 - Math.abs(i) / (r + 1));
    weights.push(k);
    sum += k;
  }
  const tmp = new Float32Array(mask.length);
  const out = new Float32Array(mask.length);
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      let acc = 0;
      for (let i = -far; i <= far; i += 1) {
        const sx = Math.min(w - 1, Math.max(0, x + i));
        acc += mask[y * w + sx] * weights[i + far];
      }
      tmp[y * w + x] = acc / sum;
    }
  }
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      let acc = 0;
      for (let i = -far; i <= far; i += 1) {
        const sy = Math.min(h - 1, Math.max(0, y + i));
        acc += tmp[sy * w + x] * weights[i + far];
      }
      out[y * w + x] = acc / sum;
    }
  }
  return out;
};
export const pcfDiscOf = (taps) => {
  const n = Math.max(1, Math.round(Number(taps) || 1));
  const out = new Float32Array(n * 2);
  const golden = Math.PI * (3 - Math.sqrt(5));
  for (let i = 0; i < n; i += 1) {
    const r = n === 1 ? 0 : Math.sqrt((i + 0.5) / n);
    const a = i * golden;
    out[i * 2] = Math.cos(a) * r;
    out[i * 2 + 1] = Math.sin(a) * r;
  }
  return out;
};
export const pcfRotationOf = (x, y) => {
  const h = Math.sin(x * 12.9898 + y * 78.233) * 43758.5453;
  return (h - Math.floor(h)) * Math.PI * 2;
};
/* SELF-SHADOWING ON THE MOLECULE ITSELF — AND WHY THERE IS NONE. Every pixel the
   camera's pass covered owns a WORLD POINT and a NORMAL — the patch of skin the
   viewer really sees. That point is pushed into the lamp's frame and compared with
   what the lamp saw FIRST at that pixel. The receiver is in its own depth map, so
   it occludes itself by exactly zero and no « footprint » trick is needed to keep
   a shadow off its own edges — that trick, plus a wide « ambient » blur of the
   mask, is what made the first version dirty the molecule.
   What is written is the OCCLUSION WEIGHTED BY THE LAMP'S SHARE:
   `occlusion · (floor + (1 − floor)·|N·L|)`. A face fully under the lamp keeps
   all of the shadow, a face the lamp grazes keeps a little (so the shadow
   stays legible on a ribbon's side wall), a face the lamp never lights keeps
   only the floor — and the mask is ZERO outside the receiver's own coverage, so
   the background is never touched. */
export const shadowMaskOf = ({
  camera, light, lightDir = [0, 0, 1], width, height, biasNdc = 0, softness = 0,
  taps = 1, penumbra = 0, penumbraMax = 0, depthScale = 0, facingFloor = 0,
}) => {
  const w = Math.max(1, Math.round(width));
  const h = Math.max(1, Math.round(height));
  const mask = new Float32Array(w * h);
  const base = Math.max(0, Number(softness) || 0);
  const grow = Math.max(0, Number(penumbra) || 0);
  const cap = Math.max(0, Number(penumbraMax) || 0);
  const perAngstrom = Number(depthScale) > 0 ? 1 / Number(depthScale) : 0;
  const normals = camera.normal || null;
  const floor = Math.min(1, Math.max(0, Number(facingFloor) || 0));
  const L = normalize3(lightDir);
  const discCache = new Map();
  const discOf = (n) => {
    let d = discCache.get(n);
    if (!d) { d = pcfDiscOf(n); discCache.set(n, d); }
    return d;
  };
  const discTaps = Math.max(1, Math.round(Number(taps) || 1));
  const clipX = (x) => Math.min(w - 1, Math.max(0, x));
  const clipY = (y) => Math.min(h - 1, Math.max(0, y));
  const clipPt = new Array(4);
  const scr = new Array(3);
  let shadowed = 0, penumbraRadius = 0, maxTaps = 0, facingSum = 0, facingCount = 0;
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      const idx = y * w + x;
      if (!camera.hit[idx]) continue;
      const p = clipToScreen(mat4TransformPoint(light.clip, [
        camera.world[idx * 3], camera.world[idx * 3 + 1], camera.world[idx * 3 + 2],
      ], clipPt), w, h, scr);
      if (!p) continue;
      const lx = clipX(Math.floor(p[0]));
      const ly = clipY(Math.floor(p[1]));
      const nearest = light.depth[ly * w + lx];
      /* ⚠ THE CENTRE RAY IS NOT A GATE. A penumbra is precisely the case where the
         centre ray MISSES the occluder while the rays around it hit it: skipping
         the pixel here would erase the whole soft edge — and with it the shadow of
         anything thinner than the disc. The DISC decides; the centre ray only
         measures the GAP that PCSS grows the disc by. */
      const gap = nearest < 2 ? p[2] - nearest : 0;
      /* THE DISC IS THE SOFTNESS, PLUS WHAT THE GAP ADDS (PCSS). A soft edge is a
         WIDTH the user chose; the depth gap between the receiver and the occluder
         only pushes the disc further (PCSS: a contact shadow stays crisp while a
         cast shadow spreads). `blur: 0` therefore gives the hard step of a plain
         shadow map — the radius is 0 and the centre ray decides. */
      const radius = Math.min(cap > 0 ? cap : Infinity,
        base + (grow > 0 && gap > biasNdc ? grow * gap * perAngstrom : 0));
      let occluded = 0;
      if (radius > 0) {
        if (radius > penumbraRadius) penumbraRadius = radius;
        const need = Math.min(SHADOW_MAX_TAPS, Math.max(discTaps, Math.ceil(radius * SHADOW_TAPS_PER_PIXEL)));
        const disc = discOf(need);
        const invTaps = 1 / need;
        if (need > maxTaps) maxTaps = need;
        const rot = pcfRotationOf(x, y);
        const cs = Math.cos(rot), sn = Math.sin(rot);
        for (let t = 0; t < disc.length; t += 2) {
          const ox = disc[t] * radius, oy = disc[t + 1] * radius;
          const sx = clipX(Math.round(lx + ox * cs - oy * sn));
          const sy = clipY(Math.round(ly + ox * sn + oy * cs));
          const d = light.depth[sy * w + sx];
          if (d < 2 && p[2] > d + biasNdc) occluded += invTaps;
        }
      } else {
        if (!(gap > biasNdc)) continue;
        occluded = 1;
      }
      if (!(occluded > 0)) continue;
      let face = 1;
      if (normals) {
        const nx = normals[idx * 3], ny = normals[idx * 3 + 1], nz = normals[idx * 3 + 2];
        face = Math.abs(nx * L[0] + ny * L[1] + nz * L[2]);
        facingSum += face;
        facingCount += 1;
      }
      mask[idx] = occluded * (floor + (1 - floor) * face);
      if (occluded >= 0.5) shadowed += 1;
    }
  }
  /* ⚠ LA COUVERTURE EST UNE FRONTIÈRE, PAS UN DÉCOR. `softenMask` étale le trait de
     quelques pixels ; hors du dessin, ces pixels n'ont AUCUN point du monde, et le
     masque y multiplierait un fond blanc — le liseré sombre du rapport, mesuré :
     3 538 pixels de fond assombris sur une scène réelle. Le masque est donc ramené
     à ZÉRO partout où la passe caméra n'a rien vu : une ombre n'existe que SUR une
     surface, jamais à côté. */
  const softened = softenMask(mask, w, h, base);
  if (base > 0) {
    for (let i = 0; i < softened.length; i += 1) {
      if (!camera.hit[i]) softened[i] = 0;
    }
  }
  return {
    mask: softened, width: w, height: h, shadowed,
    taps: discTaps, tapsMax: maxTaps, penumbraRadius,
    facing: {
      floor,
      mean: facingCount ? facingSum / facingCount : 1,
      sampled: facingCount,
    },
  };
};
export const sampleMaskBilinear = (mask, mw, mh, nx, ny) => {
  const width = Math.max(1, Math.round(mw));
  const height = Math.max(1, Math.round(mh));
  const mx = Math.min(width - 1, Math.max(0, nx * width - 0.5));
  const my = Math.min(height - 1, Math.max(0, ny * height - 0.5));
  const x0 = Math.floor(mx), y0 = Math.floor(my);
  const x1 = Math.min(width - 1, x0 + 1), y1 = Math.min(height - 1, y0 + 1);
  const fx = mx - x0, fy = my - y0;
  const a = mask[y0 * width + x0], b = mask[y0 * width + x1];
  const c = mask[y1 * width + x0], d = mask[y1 * width + x1];
  return (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy;
};
export const applyShadowToPixels = (data, width, height, mask, maskWidth, maskHeight, strength) => {
  const s = Math.min(1, Math.max(0, Number(strength) || 0));
  if (!(s > 0) || !data || !mask) return 0;
  const w = Math.max(1, Math.round(width));
  const h = Math.max(1, Math.round(height));
  let touched = 0;
  for (let y = 0; y < h; y += 1) {
    const ny = (y + 0.5) / h;
    for (let x = 0; x < w; x += 1) {
      const m = sampleMaskBilinear(mask, maskWidth, maskHeight, (x + 0.5) / w, ny);
      if (!(m > 0.002)) continue;
      const f = 1 - s * m;
      const i = (y * w + x) * 4;
      const r = Math.round(data[i] * f);
      const g = Math.round(data[i + 1] * f);
      const b = Math.round(data[i + 2] * f);
      if (r === data[i] && g === data[i + 1] && b === data[i + 2]) continue;
      data[i] = r; data[i + 1] = g; data[i + 2] = b;
      touched += 1;
    }
  }
  return touched;
};

// ============================================================================
// 3. LIGHT RIG & SCENE PARSING
// ============================================================================
export const lightDepthScale = ({ distance, radius, near, far } = {}) => {
  const n = Number.isFinite(Number(near)) ? Number(near) : 0.01;
  const f = Number.isFinite(Number(far)) ? Number(far) : Math.max(0.02, Number(distance) * 2 + Number(radius) * 2);
  return 2 / Math.max(1e-6, f - n);
};
export const shadowRigOf = ({
  dir, bounds = null, center = [0, 0, 0], radius = 1, distance = null,
  margin = RAY_SHADOW_DEFAULTS.fitMargin,
} = {}) => {
  const z = normalize3(dir || [0, 0, 1]);
  const box = bounds && bounds.min && bounds.max ? bounds : null;
  const c = box
    ? [(box.min[0] + box.max[0]) / 2, (box.min[1] + box.max[1]) / 2, (box.min[2] + box.max[2]) / 2]
    : [Number(center[0]) || 0, Number(center[1]) || 0, Number(center[2]) || 0];
  const r = Math.max(1e-3, Number(radius) || 1);
  const d = Math.max(1e-3, Number.isFinite(Number(distance)) ? Number(distance) : r * 100);
  const eye = [c[0] + z[0] * d, c[1] + z[1] * d, c[2] + z[2] * d];
  const up = Math.abs(z[2]) > 0.9 ? [1, 0, 0] : [0, 0, 1];
  const view = mat4LookAt(eye, c, up);
  const corners = box
    ? boxCornersOf(box)
    : boxCornersOf({ min: [c[0] - r, c[1] - r, c[2] - r], max: [c[0] + r, c[1] + r, c[2] + r] });
  let left = Infinity, right = -Infinity, bottom = Infinity, top = -Infinity;
  let near = Infinity, far = -Infinity;
  const p = new Array(4);
  for (let i = 0; i < 8; i += 1) {
    const v = mat4TransformPoint(view, corners[i], p);
    if (v[0] < left) left = v[0]; if (v[0] > right) right = v[0];
    if (v[1] < bottom) bottom = v[1]; if (v[1] > top) top = v[1];
    const depth = -v[2];
    if (depth < near) near = depth; if (depth > far) far = depth;
  }
  if (!(right > left)) right = left + 1e-3;
  if (!(top > bottom)) top = bottom + 1e-3;
  const m = Math.min(2, Math.max(1, Number(margin) || 1));
  const spanMax = Math.max(right - left, top - bottom, far - near, 1e-3);
  const padFloor = spanMax * 0.02;
  const padX = Math.max(padFloor, ((right - left) * (m - 1)) / 2);
  const padY = Math.max(padFloor, ((top - bottom) * (m - 1)) / 2);
  const padZ = Math.max(padFloor, (padX + padY) / 2);
  const nz = Math.max(1e-3, near - padZ);
  const fz = Math.max(nz + 1e-3, far + padZ);
  const l = left - padX, rt = right + padX, bt = bottom - padY, tp = top + padY;
  const proj = mat4Orthographic(l, rt, bt, tp, nz, fz);
  return {
    view, proj, clip: mat4Multiply(proj, view),
    left: l, right: rt, bottom: bt, top: tp, near: nz, far: fz,
    width: rt - l, height: tp - bt, depthScale: 2 / (fz - nz),
    center: c, radius: r, distance: d, margin: m,
  };
};
export const lightMatricesOf = (setup) => shadowRigOf(setup);
export const lightClipMatrix = (setup) => lightMatricesOf(setup).clip;
const elements16Of = (matrix) => {
  const e = matrix && matrix.elements ? matrix.elements : matrix;
  if (!e || typeof e.length !== 'number' || e.length !== 16) return null;
  return Array.from(e);
};
export const viewerMatrixOf = (stage) => {
  const viewer = stage && stage.viewer;
  if (!viewer) return null;
  const rot = elements16Of(viewer.rotationGroup && viewer.rotationGroup.matrix);
  const pos = viewer.translationGroup && viewer.translationGroup.position;
  const tx = pos ? Number(pos.x) || 0 : 0;
  const ty = pos ? Number(pos.y) || 0 : 0;
  const tz = pos ? Number(pos.z) || 0 : 0;
  if (!rot && !tx && !ty && !tz) return null;
  const t = mat4Identity();
  t[12] = tx; t[13] = ty; t[14] = tz;
  return rot ? mat4Multiply(rot, t) : t;
};
/* WHAT IS DRAWN, AND ONLY THAT. This viewer hides a molecule by NOT building its
   representations, while the component itself stays `visible` and its Structure
   still holds every atom. Reading the structure therefore made a hidden membrane
   cast a shadow of itself — « I see a projected membrane although the membrane is
   NOT visible » — so the shadow reads the `structureView` of the living
   representations instead: a molecule that has been hidden draws nothing, so it casts nothing.
   `null` means "everything is drawn" (the caller keeps the atoms, never invents a hole). */
const drawnAtomIndicesOf = (comp, atomCount) => {
  const list = comp && comp.reprList;
  if (!Array.isArray(list)) return null;
  const set = new Set();
  list.forEach((el) => {
    try {
      const rep = (el && (el.repr || el)) || null;
      if (!rep || rep.visible === false) return;
      if (opacityOf(rep, el) <= INVISIBLE_OPACITY) return;
      const sv = rep.structureView;
      if (!sv || typeof sv.getAtomIndices !== 'function') return;
      const idx = sv.getAtomIndices();
      if (!idx || !idx.length) return;
      for (let i = 0; i < idx.length; i += 1) set.add(idx[i]);
    } catch { }
  });
  if (set.size && atomCount && set.size >= atomCount) return null;
  return [...set].sort((a, b) => a - b);
};
export const repTypeOf = (rep, el = null) => {
  let fromEl = '';
  if (el) {
    fromEl = el.name || (typeof el.getType === 'function' ? el.getType() : '');
  }
  const raw = (rep && rep.type) || fromEl || (rep && rep.parameters && rep.parameters.type) || '';
  return String(raw).toLowerCase();
};
export const repKindOf = (rep, el = null) => {
  const stroke = PROXY_STROKE_BY_TYPE[repTypeOf(rep, el)];
  return stroke ? stroke.kind : '';
};
const repNumber = (rep, el, ...keys) => {
  const sources = [rep, el && el.parameters, rep && rep.parameters];
  for (let s = 0; s < sources.length; s += 1) {
    const source = sources[s];
    if (!source) continue;
    for (let k = 0; k < keys.length; k += 1) {
      const v = Number(source[keys[k]]);
      if (Number.isFinite(v) && v > 0) return v;
    }
  }
  return 0;
};
export const proxyRadiusOf = (rep, vdwRadius = 1.7, el = null) => {
  const stroke = PROXY_STROKE_BY_TYPE[repTypeOf(rep, el)];
  if (!stroke) return null;
  const vdw = Math.max(0.1, Number(vdwRadius) || 1.7);
  const radiusScale = repNumber(rep, el, 'radiusScale', 'sphereScale', 'scale');
  const radiusSize = repNumber(rep, el, 'radiusSize', 'radius');
  const aspect = repNumber(rep, el, 'aspectRatio');
  const radiusType = String((rep && rep.radiusType) || '').toLowerCase();
  const sizeType = radiusType === '' || radiusType === 'size';
  const core = (fallback) => {
    if (radiusSize > 0 && (sizeType || radiusScale <= 0)) return radiusSize;
    if (radiusScale > 0) return vdw * radiusScale;
    return fallback;
  };
  let r;
  switch (stroke.kind) {
    case 'vdw': r = core(vdw); break;
    case 'ball': r = core(stroke.core) * (aspect || stroke.aspect); break;
    case 'bond': r = core(stroke.core); break;
    case 'spline':
      r = radiusScale > 0 ? stroke.base * (radiusScale / stroke.scale) : stroke.base;
      if (radiusSize > 0 && sizeType) r = Math.max(r, radiusSize);
      break;
    case 'tube':
      r = sizeType && radiusSize > 0 ? radiusSize : (radiusScale > 0 ? stroke.base * radiusScale : stroke.base);
      break;
    default: r = stroke.min;
  }
  return Math.max(0.05, Math.max(stroke.min, r));
};
const atomProxyOf = (structure) => {
  try {
    if (!structure || typeof structure.getAtomProxy !== 'function') return null;
    const ap = structure.getAtomProxy();
    return ap && typeof ap.isBackbone === 'function' ? ap : null;
  } catch { return null; }
};
const drawsBackboneOf = (ap, idx) => {
  if (!ap) return false;
  try {
    for (let i = 0; i < idx.length; i += 1) {
      const a = idx[i];
      if (!(a >= 0)) continue;
      ap.index = a;
      if (ap.isBackbone()) return true;
    }
  } catch { return false; }
  return false;
};
/* ⚠ A STROKE OWNS ONLY WHAT IT DRAWS — « spheric shadows for bonds » was the
   report, and on the picture the round balls fell exactly on the CYCLES and on the
   BRANCHES of the side chains. The cause: NGL's Tube of the backbone and the
   Licorice of the side chains SHARE ONE SELECTION, and `StructureView#getAtomIndices`
   returns the WHOLE list of that selection, side chains included. A « chain » kind
   (BACKBONE_ONLY_KINDS — spline / tube) therefore answers for the backbone atoms
   only, asking the very question NGL asks itself (`AtomProxy#isBackbone()` →
   `residueType.backboneIndexList`, the list the cartoon and the tube build their
   geometry from): the other atoms of the list it shares with the sticks are drawn by the sticks,
   at THEIR own stroke. */
export const drawnProxyRadiiOf = (comp, atomCount, vdw = null, links = null, splines = null, covered = null) => {
  const list = comp && comp.reprList;
  if (!Array.isArray(list)) return null;
  const out = new Float32Array(Math.max(0, Math.round(Number(atomCount) || 0)));
  if (!out.length) return out;
  out.fill(NaN);
  const ap = atomProxyOf(comp && comp.structure);
  list.forEach((el) => {
    try {
      const rep = (el && (el.repr || el)) || null;
      if (!rep || rep.visible === false) return;
      /* ⚠ A REPRESENTATION WHOSE REAL TRIANGLES WERE READ NEEDS NO PROXY. The
         triangles ARE the drawn shape (see worldTrianglesOf) — a ball at an atom or
         a capsule along a link would only ADD a rim the drawing does not have.
         Measured in Chrome: without this, the 0.45 Å balls of a cartoon put 1 756
         fully shadowed pixels on the white background, up to 6 px from the ribbon.
         The proxy stays for the case it was made for: a draw whose geometry cannot
         be read yet (a build still in NGL's queue). */
      if (covered && covered.has(el)) return;
      const op = opacityOf(rep, el);
      if (op <= INVISIBLE_OPACITY) return;
      const sv = rep.structureView;
      if (!sv || typeof sv.getAtomIndices !== 'function') return;
      const idx = sv.getAtomIndices();
      if (!idx || !idx.length) return;
      const kind = repKindOf(rep, el);
      const linked = LINKED_KINDS[kind] === 1;
      const chainOnly = BACKBONE_ONLY_KINDS[kind] === 1 && drawsBackboneOf(ap, idx);
      for (let i = 0; i < idx.length; i += 1) {
        const a = idx[i];
        if (!(a >= 0 && a < out.length)) continue;
        if (chainOnly) {
          ap.index = a;
          if (!ap.isBackbone()) continue;    // the spline does not draw here
          /* ⚠ A SPLINE RUNS THROUGH THE *TRACE* ATOMS, NOT THROUGH THE BACKBONE
             BLOCK. A cartoon is a surface built on the trace (the CA of a protein,
             `residue.traceAtomIndex`); a ball on the N or the C sits ~1.2 Å off that
             path and therefore OUTSIDE the drawn ribbon. Measured on a real NGL
             stage in Chrome: those balls put 1 335 fully shadowed pixels on the
             white background, up to 2 Å away from the ribbon — the « dirt » of the
             report. Only the trace atom is the drawn shape of a spline, and it is
             the only one the trace chain below links. */
          if (!(ap.residue && ap.residue.traceAtomIndex === a)) continue;
          if (splines) splines[a] = 1;
        }
        const per = proxyRadiusOf(rep, vdw ? vdw[a] : 1.7, el);
        if (per == null) continue;
        const seen = op < 1 ? per * op : per;
        if (!(out[a] >= seen)) out[a] = seen;
        /* A SPLINE DOES NOT DRAW BONDS: its links are its own chain (see
           drawnBondsOf), so it never marks an atom as a stick's endpoint. */
        if (linked && links && !chainOnly) links[a] = 1;
      }
    } catch { }
  });
  return out;
};
export const opacityOf = (rep, el = null) => {
  const sources = [rep, el && el.parameters, rep && rep.parameters];
  for (let s = 0; s < sources.length; s += 1) {
    const source = sources[s];
    if (!source) continue;
    const v = Number(source.opacity);
    if (Number.isFinite(v)) return Math.min(1, Math.max(0, v));
  }
  return 1;
};
/* A COMPACT VIEW OF ONE ATTRIBUTE. NGL does interleave some buffers; a reader
   that assumes `array[i * 3]` while the buffer really holds `array[i * stride +
   offset]` silently reads another attribute's numbers — which is precisely how
   the first version invented a band direction out of positions. Anything
   interleaved is therefore copied out, once, into a plain array. */
export const compactAttribute = (attr, itemSize) => {
  if (!attr || !attr.array) return null;
  const a = attr.array;
  const data = attr.data;
  if (!data || data.stride === itemSize) return { array: a, count: attr.count, stride: itemSize };
  const stride = data.stride;
  const offset = attr.offset || 0;
  const count = Math.min(attr.count, Math.max(0, Math.floor((a.length - offset) / stride)));
  const out = new Float32Array(count * itemSize);
  for (let i = 0; i < count; i += 1) {
    const base = i * stride + offset;
    for (let c = 0; c < itemSize; c += 1) out[i * itemSize + c] = a[base + c];
  }
  return { array: out, count, stride: itemSize };
};
/* ⚠ WHICH BUFFERS ARE SURFACES, AND WHICH ARE IMPOSTORS. Measured on NGL 2.4
   in a real browser: an INDEXED mesh of a drawn surface (cartoon, ribbon, tube,
   rope, surface, and the ring plates of « Stylized rings ») carries a `normal`
   attribute; an impostor (a ball, a stick, a wire, a point) carries none — its
   shape is cut out in the FRAGMENT shader from `radius` / `position1` /
   `position2`, and its vertices are the corners of a quad. So the presence of
   normals IS the discriminator: a geometry without them is never read as
   triangles, whatever its representation is called. */
export const trianglesOfGeometry = (geometry, type = '') => {
  if (!geometry || !geometry.attributes) return null;
  if (IMPOSTOR_TYPES[String(type).toLowerCase()]) return null;
  const idx = geometry.index;
  if (!idx || !idx.array || idx.array.length < 3) return null;
  const pos = compactAttribute(geometry.attributes.position, 3);
  const nor = compactAttribute(geometry.attributes.normal, 3);
  if (!pos || !pos.array || !nor || !nor.array) return null;
  if (pos.array.length < 9) return null;
  const count = Math.floor(idx.array.length / 3);
  return {
    type: String(type || '').toLowerCase(),
    positions: pos.array,
    normals: nor.array,
    indices: idx.array,
    count: Math.max(0, count),
  };
};

/* THE REAL TRIANGLES OF ONE COMPONENT, IN WORLD SPACE. Every visible
   representation contributes the indexed meshes it really draws — and so do the
   RING PLATES, whether they are reached through the representation's bufferList
   (`addBufferRepresentation` puts the MeshBuffer there) or through the
   `__plates` mark the viewer leaves on the element. Nothing is re-derived from
   the atoms: the hexagon of a base is the hexagon that was drawn. */
export const worldTrianglesOf = (comp, viewerM = null) => {
  const empty = {
    positions: new Float32Array(0), normals: new Float32Array(0), indices: new Uint32Array(0),
    count: 0, vertexCount: 0, reps: 0, plates: 0, kinds: '', debug: '', surfaces: [],
  };
  const list = comp && comp.reprList;
  if (!Array.isArray(list)) return { ...empty, debug: 'no reprList' };
  const own = elements16Of(comp.matrix);
  const m = own
    ? (viewerM ? mat4Multiply(viewerM, own) : own)
    : elements16Of(comp.group && comp.group.matrixWorld);
  const chunks = [];
  const seen = new Set();
  const kinds = [];
  const surfaces = [];
  let total = 0, plates = 0, found = 0, debug = '';
  const takeGeometry = (geometry, type, isPlate) => {
    if (!geometry || seen.has(geometry)) return;
    seen.add(geometry);
    const tri = trianglesOfGeometry(geometry, type);
    if (!tri || !tri.count) return;
    chunks.push({ tri, isPlate });
    total += tri.count;
    if (isPlate) plates += 1;
  };
  list.forEach((el) => {
    try {
      const rep = (el && (el.repr || el)) || null;
      if (!rep || rep.visible === false) return;
      if (opacityOf(rep, el) <= INVISIBLE_OPACITY) return;
      const type = repTypeOf(rep, el);
      const mark = el && el.__plates && el.__plates.mesh && el.__plates.mesh.geometry;
      const before = total;
      /* ⚠ TWO PLACES, AND BOTH ARE REAL. `StructureRepresentation#attach` copies
         what `create()` built in `dataList` into `bufferList` and hands it to the
         viewer (measured in the installed build), so an ATTACHED representation
         holds its meshes in `bufferList` — but one whose build is still queued
         (a still asked right after a load) holds them in `dataList` ONLY, and a
         reader that knew just one of the two would silently cast nothing. Reading
         both, deduplicating by geometry, is the same set of triangles either way. */
      const chunks = Array.isArray(rep.bufferList) ? rep.bufferList.slice() : [];
      if (Array.isArray(rep.dataList)) {
        rep.dataList.forEach((data) => {
          if (data && Array.isArray(data.bufferList)) data.bufferList.forEach((b) => chunks.push(b));
        });
      }
      chunks.forEach((b) => { if (b && b.geometry) takeGeometry(b.geometry, type, !!mark && b.geometry === mark); });
      if (mark) takeGeometry(mark, type, true);
      if (total > before) {
        found += 1;
        surfaces.push(el);
        if (type && !kinds.includes(type)) kinds.push(type);
      }
    } catch (e) { if (!debug) debug = `error: ${e.message}`; }
  });
  if (!total) return { ...empty, debug: debug || 'no triangle mesh drawn' };
  let vertexCount = 0;
  chunks.forEach(({ tri }) => { vertexCount += Math.floor(tri.positions.length / 3); });
  const positions = new Float32Array(vertexCount * 3);
  const normals = new Float32Array(vertexCount * 3);
  const indices = new Uint32Array(total * 3);
  let at = 0, it = 0;
  chunks.forEach(({ tri }) => {
    const p = tri.positions, nn = tri.normals, ix = tri.indices;
    const n = Math.min(Math.floor(p.length / 3), Math.floor(nn.length / 3));
    for (let i = 0; i < n; i += 1) {
      const x = p[i * 3], y = p[i * 3 + 1], z = p[i * 3 + 2];
      const nx = nn[i * 3], ny = nn[i * 3 + 1], nz = nn[i * 3 + 2];
      if (m) {
        positions[at * 3] = m[0] * x + m[4] * y + m[8] * z + m[12];
        positions[at * 3 + 1] = m[1] * x + m[5] * y + m[9] * z + m[13];
        positions[at * 3 + 2] = m[2] * x + m[6] * y + m[10] * z + m[14];
        normals[at * 3] = m[0] * nx + m[4] * ny + m[8] * nz;
        normals[at * 3 + 1] = m[1] * nx + m[5] * ny + m[9] * nz;
        normals[at * 3 + 2] = m[2] * nx + m[6] * ny + m[10] * nz;
      } else {
        positions[at * 3] = x; positions[at * 3 + 1] = y; positions[at * 3 + 2] = z;
        normals[at * 3] = nx; normals[at * 3 + 1] = ny; normals[at * 3 + 2] = nz;
      }
      at += 1;
    }
    for (let t = 0; t < tri.count * 3; t += 1) {
      const vi = ix[t];
      indices[it] = at - n + (vi < n ? vi : 0);
      it += 1;
    }
  });
  return {
    positions, normals, indices,
    count: total, vertexCount: at, reps: found, plates,
    kinds: kinds.join('·'), debug: '', surfaces,
  };
};
export const emptyTriangles = () => ({
  positions: new Float32Array(0), normals: new Float32Array(0), indices: new Uint32Array(0),
  count: 0, vertexCount: 0, reps: 0, plates: 0, kinds: '', debug: '',
});

/* THE ATOM PROXIES, AS ONE SET OF BALLS AND CAPSULES. (The old version also
   merged a « band brush » in here; the bands are REAL TRIANGLES now — see
   `fillTriangles` below — so nothing is re-derived from the atoms any more.)
   `count` is the number of BALLS — one per drawn atom — and `filled` the number
   of CAPSULES that join them along a real bond: the two halves of a stroke's
   shadow, both drawn by `rasterizeCapsules` in each pass. */
const fillDrawnLinks = (parts, stride, maxAtoms) => {
  const layouts = parts.filter((part) => part.data && part.data.position).map((part) => layOut(part, stride));
  const slots = layouts.reduce((a, lay) => a + lay.len, 0);
  const capacity = Math.max(1, Math.min(slots, maxAtoms || slots));
  const out = new Float32Array(capacity * 3);
  const radii = new Float32Array(capacity);

  const totalEdges = layouts.reduce((a, lay) => a + (lay.edges ? lay.edges.length : 0), 0);
  const edges = new Int32Array(totalEdges);
  let edgeK = 0;

  let k = 0;
  layouts.forEach((lay) => {
    const startK = k;
    for (let e = 0; e < lay.len && k < capacity; e += 1) {
      out[k * 3] = lay.wpos[e * 3];
      out[k * 3 + 1] = lay.wpos[e * 3 + 1];
      out[k * 3 + 2] = lay.wpos[e * 3 + 2];
      radii[k] = lay.wrad[e];
      k += 1;
    }
    if (lay.edges) {
      for (let p = 0; p < lay.edges.length; p += 1) {
        edges[edgeK++] = lay.edges[p] + startK;
      }
    }
  });
  return { positions: out, radii, count: k, edges, filled: Math.floor(edges.length / 2) };
};
/* THE TRIANGLES OF THE WHOLE SCENE, merged and budgeted. One accumulator for
   every component; `stride` thins the list when a system is huge (the same
   bargain as `maxAtoms` for the balls) instead of silently dropping the
   geometry of a whole molecule. */
const fillTriangles = (parts, maxTriangles) => {
  const total = parts.reduce((a, part) => a + (part.tris ? part.tris.count : 0), 0);
  if (!total) return { ...emptyTriangles(), stride: 1, total: 0 };
  const cap = Math.max(1, Math.round(Number(maxTriangles) || total));
  const stride = total > cap ? Math.ceil(total / cap) : 1;
  const drawn = Math.ceil(total / stride);
  const vertexCount = parts.reduce((a, part) => a + (part.tris ? part.tris.vertexCount : 0), 0);
  const positions = new Float32Array(vertexCount * 3);
  const normals = new Float32Array(vertexCount * 3);
  const indices = new Uint32Array(drawn * 3);
  let at = 0, it = 0, kept = 0, plates = 0, reps = 0;
  const kinds = [];
  parts.forEach((part) => {
    const tri = part.tris;
    if (!tri || !tri.count) return;
    reps += tri.reps;
    plates += tri.plates;
    if (tri.kinds) tri.kinds.split('·').forEach((k) => { if (k && !kinds.includes(k)) kinds.push(k); });
    const base = at;
    positions.set(tri.positions, at * 3);
    normals.set(tri.normals, at * 3);
    at += tri.vertexCount;
    for (let t = 0; t < tri.count; t += stride) {
      if (kept >= drawn) break;
      indices[it] = tri.indices[t * 3] + base;
      indices[it + 1] = tri.indices[t * 3 + 1] + base;
      indices[it + 2] = tri.indices[t * 3 + 2] + base;
      it += 3;
      kept += 1;
    }
  });
  return {
    positions, normals, indices,
    count: kept, vertexCount: at, reps, plates,
    kinds: kinds.join('·'), debug: '', stride, total,
  };
};

/* THE GRAPH OF LINKS BETWEEN THE DRAWN ATOMS. It is read from the STRUCTURE
   (`eachBond` → `atomIndex1` / `atomIndex2`, which NGL builds from the residue
   templates AND from the peptide bond it checks by distance) and never invented
   out of "the next atom of the list": that list is the whole selection, so the
   atom after a backbone oxygen is a side-chain carbon, and filling it drew the
   ghost disc of the report.
   A pair is a link only when BOTH its atoms are drawn by a stroke, and only when
   it is a BOND — closer than LINK_MAX (a residue template can join two CAs two
   residues apart, and a stroke drawn across the molecule is a link no eye sees).
   A stroke drawn without its links alone leaves holes ångströms wide that no ray can hit
   — measured: 0 shadowed pixels on 3655, against 3160 on 12247 once the links are
   filled — and THAT is the graph of the structure that is followed here
   (`eachBond`), never « the next atom of the list », which filled ghost bonds.
   When the structure declares no graph at all, the only fallback is the polymer
   TRACE (the trace atom of CONSECUTIVE residues), which is where a ribbon's
   continuity actually lives. */
const drawnBondsOf = (structure, links, n, positions = null, splines = null) => {
  if (!structure || typeof structure.eachBond !== 'function') return [];
  const out = [];
  const seen = new Set();
  const isBond = (a, b) => {
    if (!positions) return true;
    const dx = positions[a * 3] - positions[b * 3];
    const dy = positions[a * 3 + 1] - positions[b * 3 + 1];
    const dz = positions[a * 3 + 2] - positions[b * 3 + 2];
    return dx * dx + dy * dy + dz * dz <= LINK_MAX * LINK_MAX;
  };
  const addBond = (a, b) => {
    if (!(a >= 0 && a < n && b >= 0 && b < n) || a === b) return;
    if (links[a] !== 1 || links[b] !== 1) return;
    if (!isBond(a, b)) return;
    const key = a < b ? a * n + b : b * n + a;
    if (seen.has(key)) return;
    seen.add(key);
    out.push(a, b);
  };
  let linked = false;
  for (let i = 0; i < n && !linked; i += 1) linked = links[i] === 1;
  if (linked) {
    try {
      structure.eachBond((bond) => { addBond(bond.atomIndex1, bond.atomIndex2); });
    } catch { }
    if (out.length === 0) {
      try {
        if (typeof structure.eachPolymer === 'function') {
          structure.eachPolymer((p) => {
            let prevTrace = -1;
            p.eachResidue((r) => {
              const trace = r.traceAtomIndex;
              if (trace !== undefined && trace >= 0) {
                if (prevTrace >= 0) addBond(prevTrace, trace);
                prevTrace = trace;
              }
            });
          });
        }
      } catch { }
    }
  }
  /* AND THE SPLINE'S OWN CHAIN, ALWAYS — a cartoon/ribbon/tube draws a CONTINUOUS
     surface along the trace atoms, so those atoms are linked to each other whether
     or not the structure's bond graph happens to join them (it joins C(i) to N(i+1),
     two atoms the ribbon does not pass through). `splines` is the mark
     `drawnProxyRadiiOf` leaves on the atoms a spline really draws. */
  let anySpline = false;
  if (splines) {
    for (let i = 0; i < n && !anySpline; i += 1) anySpline = splines[i] === 1;
  }
  if (anySpline) {
    const addTrace = (a, b) => {
      if (!(splines[a] === 1 && splines[b] === 1)) return;
      if (!isBond(a, b)) return;
      const key = a < b ? a * n + b : b * n + a;
      if (seen.has(key)) return;
      seen.add(key);
      out.push(a, b);
    };
    /* ⚠ ON MARCHE LES CHAÎNES, PAS LES POLYMÈRES. `eachPolymer` ne rend un polymère
       que pour un enchaînement RÉEL de résidus (mesuré : RIEN pour un dipeptide dont
       les coordonnées ne font pas une liaison peptidique parfaite), alors qu'un ruban
       se dessine sur n'importe quelle chaîne de résidus. La marche est donc faite
       chaîne par chaîne — un changement de chaîne ROMPT le trait — et la trace d'un
       résidu sans atome de trace le rompt aussi. */
    const linkChain = (traces) => {
      let prev = -1;
      traces.forEach((trace) => {
        if (trace === undefined || trace < 0) { prev = -1; return; }
        if (prev >= 0) addTrace(prev, trace);
        prev = trace;
      });
    };
    try {
      const chains = [];
      if (typeof structure.eachChain === 'function') {
        structure.eachChain((chain) => {
          const traces = [];
          if (chain && typeof chain.eachResidue === 'function') {
            chain.eachResidue((r) => traces.push(r.traceAtomIndex));
          }
          chains.push(traces);
        });
      }
      if (!chains.length && typeof structure.eachResidue === 'function') {
        const traces = [];
        structure.eachResidue((r) => traces.push(r.traceAtomIndex));
        chains.push(traces);
      }
      chains.forEach(linkChain);
    } catch { }
  }
  return out;
};

const layOut = (part, stride) => {
  const slotOf = new Map();
  const own = elements16Of(part.comp.matrix);
  const m = own
    ? (part.viewerM ? mat4Multiply(part.viewerM, own) : own)
    : elements16Of(part.comp.group && part.comp.group.matrixWorld);
  const pos = part.data.position, rad = part.data.radius;
  const surface = part.surface, links = part.links;
  let measurable = false;
  if (surface) {
    for (let i = 0; i < surface.length && !measurable; i += 1) {
      measurable = Number.isFinite(surface[i]) && surface[i] > 0;
    }
  }
  const count = part.drawn ? part.drawn.length : part.n;
  const len = Math.max(0, Math.ceil(count / stride));
  const wpos = new Float32Array(Math.max(1, len) * 3);
  const wrad = new Float32Array(Math.max(1, len));
  const wlink = new Uint8Array(Math.max(1, len));
  let e = 0;
  for (let c = 0; c < count && e < len; c += stride) {
    const i = part.drawn ? part.drawn[c] : c;
    if (!(i >= 0 && i < part.n)) continue;
    const x = pos[i * 3], y = pos[i * 3 + 1], z = pos[i * 3 + 2];
    if (m) {
      wpos[e * 3] = m[0] * x + m[4] * y + m[8] * z + m[12];
      wpos[e * 3 + 1] = m[1] * x + m[5] * y + m[9] * z + m[13];
      wpos[e * 3 + 2] = m[2] * x + m[6] * y + m[10] * z + m[14];
    } else {
      wpos[e * 3] = x; wpos[e * 3 + 1] = y; wpos[e * 3 + 2] = z;
    }
    const vdw = rad && Number.isFinite(rad[i]) ? rad[i] : 1.7;
    const stroke = surface ? surface[i] : NaN;
    if (surface && measurable && !(Number.isFinite(stroke) && stroke > 0)) continue;
    const drawn = Number.isFinite(stroke) && stroke > 0;
    wrad[e] = drawn ? stroke : vdw;
    wlink[e] = drawn && links && links[i] === 1 ? 1 : 0;
    slotOf.set(i, e);
    e += 1;
  }
  const maxPairs = part.bonds ? part.bonds.length / 2 : 0;
  const edges = new Int32Array(Math.max(0, maxPairs) * 2);
  let p = 0;
  if (part.bonds) {
    for (let b = 0; b + 1 < part.bonds.length; b += 2) {
      const sa = slotOf.get(part.bonds[b]);
      const sb = slotOf.get(part.bonds[b + 1]);
      if (sa === undefined || sb === undefined) continue;
      edges[p] = sa; edges[p + 1] = sb;
      p += 2;
    }
  }
  return {
    wpos, wrad, wlink, len: e,
    edges: p === edges.length ? edges : edges.subarray(0, p),
  };
};

export const atomsFromStage = (stage, maxAtoms = RAY_SHADOW_DEFAULTS.maxAtoms, maxTriangles = RAY_SHADOW_DEFAULTS.maxTriangles) => {
  const comps = (stage && stage.compList) || [];
  const viewerM = viewerMatrixOf(stage);
  const parts = [];
  let total = 0;
  comps.forEach((comp) => {
    try {
      if (!comp || comp.visible === false) return;
      const tris = worldTrianglesOf(comp, viewerM);
      const structure = comp.structure;
      if (!structure || typeof structure.getAtomData !== 'function') {
        if (tris.count) parts.push({ comp, tris, n: 0 });
        return;
      }
      const data = structure.getAtomData({ what: { position: true, radius: true } });
      if (!data || !data.position || !data.position.length) {
        if (tris.count) parts.push({ comp, tris, n: 0 });
        return;
      }
      const n = Math.floor(data.position.length / 3);
      if (!n) return;
      const drawn = drawnAtomIndicesOf(comp, structure.atomCount || n);
      if (drawn && !drawn.length) return;
      const links = new Uint8Array(n);
      const splines = new Uint8Array(n);
      const surface = drawnProxyRadiiOf(comp, n, data.radius, links, splines, new Set(tris.surfaces || []));
      const bonds = drawnBondsOf(structure, links, n, data.position, splines);
      parts.push({ comp, data, n, drawn, surface, links, viewerM, bonds, tris });
      total += drawn ? drawn.length : n;
    } catch { }
  });
  const stride = total > maxAtoms ? Math.ceil(total / maxAtoms) : 1;
  return {
    ...fillDrawnLinks(parts, stride, maxAtoms),
    tris: fillTriangles(parts, maxTriangles),
    stride,
    total,
  };
};
export const cameraFromViewer = (viewer) => {
  const cam = (viewer && (viewer.camera || viewer.perspectiveCamera || viewer.orthographicCamera)) || null;
  const viewOffset = cam && cam.view;
  if (viewOffset && viewOffset.enabled === true) {
    throw new Error('the camera is inside a tile of a ✨ Ray still (setViewOffset) — read it before the render');
  }
  const proj = cam ? elements16Of(cam.projectionMatrix) : null;
  const view = cam ? elements16Of(cam.matrixWorldInverse) : null;
  if (!proj || !view) throw new Error('the viewer has no camera to cast a shadow from');
  return { projection: proj, view, clip: mat4Multiply(proj, view), type: (cam && cam.type) || 'Camera' };
};
export const rayShadowInputsOf = (stage, { lightDir = [0, 0, 1], options = {} } = {}) => {
  const o = rayShadowOptions(options);
  const viewer = stage && stage.viewer;
  const atoms = atomsFromStage(stage, o.maxAtoms, o.maxTriangles);
  const tris = atoms.tris || emptyTriangles();
  if (!atoms.count && !tris.count) throw new Error('nothing to cast a shadow from');
  const camera = cameraFromViewer(viewer);
  /* THE FRAME HOLDS EVERYTHING THAT CASTS OR RECEIVES: the balls (WIDENED BY THEIR
     OWN RADII — a solid reaches past its centre, see expandBoxOf) and the real
     triangles (a band or a plate can stick out of the atoms' box). */
  const boxA = atoms.count
    ? expandBoxOf(boundsBoxOf(atoms.positions, atoms.count), maxStrokeRadiusOf(atoms) * o.sphereScale)
    : null;
  const boxB = tris.count ? boundsBoxOf(tris.positions, tris.vertexCount) : null;
  const bounds = unionBoxOf(boxA, boxB);
  const center = [
    (bounds.min[0] + bounds.max[0]) / 2,
    (bounds.min[1] + bounds.max[1]) / 2,
    (bounds.min[2] + bounds.max[2]) / 2,
  ];
  const radius = Math.max(1e-3, 0.5 * Math.sqrt(
    (bounds.max[0] - bounds.min[0]) ** 2
    + (bounds.max[1] - bounds.min[1]) ** 2
    + (bounds.max[2] - bounds.min[2]) ** 2,
  ));
  const dir = normalize3(lightDir);
  const distance = radius * 100;
  const light = {
    dir, center, radius, distance, bounds,
    ...shadowRigOf({ dir, bounds, center, radius, distance, margin: o.fitMargin }),
  };
  return { atoms, camera, light, options: o };
};

// ============================================================================
// 4. OPTIONS, BLUR SCALING & DOM INTEGRATION
// ============================================================================
export const rayShadowOptions = (options = {}) => {
  const d = RAY_SHADOW_DEFAULTS;
  const num = (v, fallback) => (Number.isFinite(Number(v)) ? Number(v) : fallback);
  const span = (v, fallback, lo, hi) => Math.min(hi, Math.max(lo, num(v, fallback)));
  const blur = span(options.blur, d.blur, 0, 4);
  const soft = (v, fallback) => (v == null ? fallback * blur : num(v, fallback * blur));
  return {
    strength: span(options.strength, d.strength, 0, 1),
    softness: Math.max(0, soft(options.softness, d.softness)),
    maskMaxWidth: Math.max(64, Math.round(num(options.maskMaxWidth, d.maskMaxWidth))),
    bias: num(options.bias, d.bias),
    sphereScale: Math.max(0.1, num(options.sphereScale, d.sphereScale)),
    maxAtoms: Math.max(1, Math.round(num(options.maxAtoms, d.maxAtoms))),
    maxTriangles: Math.max(1, Math.round(num(options.maxTriangles, d.maxTriangles))),
    fitMargin: span(options.fitMargin, d.fitMargin, 1, 2),
    pcfTaps: span(Math.round(num(options.pcfTaps, d.pcfTaps)), d.pcfTaps, 1, 32),
    penumbra: Math.max(0, soft(options.penumbra, d.penumbra)),
    penumbraMax: Math.max(0, soft(options.penumbraMax, d.penumbraMax)),
    facingFloor: span(options.facingFloor, d.facingFloor, 0, 1),
    blur,
  };
};
export const rayShadowMaskSize = (width, height, options = {}) => {
  const o = rayShadowOptions(options);
  const w = Math.max(1, Math.round(Number(width) || 0));
  const h = Math.max(1, Math.round(Number(height) || 0));
  const scale = Math.min(1, o.maskMaxWidth / Math.max(1, w));
  return {
    width: Math.max(2, Math.round(w * scale)),
    height: Math.max(2, Math.round(h * scale)),
    scale,
  };
};
export const shadowBlurScale = (pxPerAngstrom, minStrokeRadius) => {
  const px = Number(pxPerAngstrom);
  const base = (!Number.isFinite(px) || px <= 0) ? 1 : Math.min(1, Math.max(SHADOW_BLUR_MIN, px / SHADOW_BLUR_REF));
  const r = Number(minStrokeRadius);
  if (!(r > 0) || !(px > 0)) return base;
  const refPx = (RAY_SHADOW_DEFAULTS.softness + RAY_SHADOW_DEFAULTS.penumbraMax) * base;
  if (!(refPx > 0)) return base;
  const capPx = r * SHADOW_BLUR_STROKE_FRACTION * px;
  return base * Math.min(1, capPx / refPx);
};
const minStrokeRadiusOf = (atoms) => {
  const radii = atoms && atoms.radii;
  const n = Math.max(0, Math.min(Number(atoms && atoms.count) || 0, radii ? radii.length : 0));
  let min = Infinity;
  for (let i = 0; i < n; i += 1) {
    const v = radii[i];
    if (v > 0 && v < min) min = v;
  }
  return Number.isFinite(min) ? min : 0;
};
/* THE OTHER END OF THE SAME MEASURE — the WIDEST stroke drawn, which is how far a
   ball reaches past its own centre (see expandBoxOf). */
export const maxStrokeRadiusOf = (atoms) => {
  const radii = atoms && atoms.radii;
  const n = Math.max(0, Math.min(Number(atoms && atoms.count) || 0, radii ? radii.length : 0));
  let max = 0;
  for (let i = 0; i < n; i += 1) {
    const v = radii[i];
    if (v > max) max = v;
  }
  return max;
};
export const maskScalePerAngstrom = ({ clip, view, bounds, width, height } = {}) => {
  if (!clip || !view) return 0;
  const w = Math.max(1, Math.round(Number(width) || 0));
  const h = Math.max(1, Math.round(Number(height) || 0));
  const corners = boxCornersOf(bounds);
  let pxMinX = Infinity, pxMaxX = -Infinity, pxMinY = Infinity, pxMaxY = -Infinity;
  let vMinX = Infinity, vMaxX = -Infinity, vMinY = Infinity, vMaxY = -Infinity;
  let seen = 0;
  for (let i = 0; i < 8; i += 1) {
    const c = corners[i];
    const world = [c[0], c[1], c[2], 1];
    const v = mat4TransformPoint(view, world);
    if (v[0] < vMinX) vMinX = v[0]; if (v[0] > vMaxX) vMaxX = v[0];
    if (v[1] < vMinY) vMinY = v[1]; if (v[1] > vMaxY) vMaxY = v[1];
    const s = clipToScreen(mat4TransformPoint(clip, world), w, h);
    if (!s) continue;
    if (s[0] < pxMinX) pxMinX = s[0]; if (s[0] > pxMaxX) pxMaxX = s[0];
    if (s[1] < pxMinY) pxMinY = s[1]; if (s[1] > pxMaxY) pxMaxY = s[1];
    seen += 1;
  }
  if (seen < 2) return 0;
  const sx = vMaxX - vMinX > 1e-6 ? (pxMaxX - pxMinX) / (vMaxX - vMinX) : Infinity;
  const sy = vMaxY - vMinY > 1e-6 ? (pxMaxY - pxMinY) / (vMaxY - vMinY) : Infinity;
  const scale = Math.min(sx, sy);
  return Number.isFinite(scale) && scale > 0 ? scale : 0;
};
export const proxyStrokeSummary = (radii, count, max = 4) => {
  const n = Math.max(0, Math.min(Math.round(Number(count) || 0), radii ? radii.length : 0));
  const bins = new Map();
  for (let i = 0; i < n; i += 1) {
    const r = Number(radii[i]);
    if (!(r > 0)) continue;
    const key = Math.round(r * 100) / 100;
    bins.set(key, (bins.get(key) || 0) + 1);
  }
  const all = [...bins.entries()].map(([radius, hits]) => ({ radius, hits })).sort((a, b) => (b.hits - a.hits) || (a.radius - b.radius));
  const cap = Math.max(1, Math.round(Number(max) || 1));
  return {
    list: all.slice(0, cap),
    rest: all.slice(cap).reduce((s, e) => s + e.hits, 0),
    count: n,
  };
};

export const buildRayShadowMask = ({ atoms, camera, light, width, height, options = {} }) => {
  const o = rayShadowOptions(options);
  const { width: mw, height: mh } = rayShadowMaskSize(width, height, o);
  const pxPerAngstrom = maskScalePerAngstrom({
    clip: camera.clip, view: camera.view, bounds: light.bounds, width: mw, height: mh,
  });
  const blurScale = shadowBlurScale(pxPerAngstrom, minStrokeRadiusOf(atoms));
  const blurOf = (name, value) => (options && options[name] !== undefined ? value : value * blurScale);
  const blur = {
    scale: blurScale, pxPerAngstrom,
    softness: blurOf('softness', o.softness),
    penumbra: blurOf('penumbra', o.penumbra),
    penumbraMax: blurOf('penumbraMax', o.penumbraMax),
  };
  const cameraAxes = viewAxesOf(camera.view || mat4Identity());
  const lightAxes = viewAxesOf(light.view || mat4Identity());
  const tris = atoms && atoms.tris && atoms.tris.count ? atoms.tris : null;

  /* THE CAMERA'S PASS — the receiver. It keeps, per pixel, the point of the
     surface the viewer really sees and its normal. Nothing else: the depth is
     only the tie-breaker between two shapes that overlap on screen. */
  const cameraPass = rasterizeSpheres({
    positions: atoms.positions, radii: atoms.radii, count: atoms.count,
    clip: camera.clip, width: mw, height: mh, radiusScale: o.sphereScale,
    right: cameraAxes.right, up: cameraAxes.up, back: cameraAxes.back,
  });
  if (atoms.edges && atoms.edges.length) {
    rasterizeCapsules({
      positions: atoms.positions, radii: atoms.radii, edges: atoms.edges,
      clip: camera.clip, width: mw, height: mh, radiusScale: o.sphereScale,
      right: cameraAxes.right, up: cameraAxes.up, back: cameraAxes.back,
    }, cameraPass);
  }
  if (tris) {
    rasterizeTriangles({
      positions: tris.positions, normals: tris.normals, indices: tris.indices,
      count: tris.count, clip: camera.clip, width: mw, height: mh, stride: tris.stride || 1,
    }, cameraPass);
  }

  /* THE LAMP'S PASS — the same shapes, orthographic, keeping the depth of the
     same surface points. ⚠ ONLY ITS DEPTH IS KEPT: the lamp is asked where the
     light stops, never which way a surface faces (that is the CAMERA's normal),
     so the world points and the normals of a megapixel map are not built at
     all — two Float32Arrays of `w × h × 3` that nothing would read. */
  const lightPass = rasterizeSpheres({
    positions: atoms.positions, radii: atoms.radii, count: atoms.count,
    clip: light.clip, width: mw, height: mh, radiusScale: o.sphereScale,
    right: lightAxes.right, up: lightAxes.up, back: lightAxes.back,
    needWorld: false, needNormal: false,
  });
  if (atoms.edges && atoms.edges.length) {
    rasterizeCapsules({
      positions: atoms.positions, radii: atoms.radii, edges: atoms.edges,
      clip: light.clip, width: mw, height: mh, radiusScale: o.sphereScale,
      right: lightAxes.right, up: lightAxes.up, back: lightAxes.back,
      needWorld: false, needNormal: false,
    }, lightPass);
  }
  if (tris) {
    rasterizeTriangles({
      positions: tris.positions, normals: tris.normals, indices: tris.indices,
      count: tris.count, clip: light.clip, width: mw, height: mh, stride: tris.stride || 1,
      needWorld: false, needNormal: false,
    }, lightPass);
  }

  const depthScale = Number(light.depthScale) > 0 ? light.depthScale : lightDepthScale(light);
  const out = shadowMaskOf({
    camera: cameraPass,
    light: { clip: light.clip, depth: lightPass.depth },
    lightDir: light.dir,
    width: mw, height: mh,
    biasNdc: o.bias * depthScale,
    softness: blur.softness, taps: o.pcfTaps,
    penumbra: blur.penumbra, penumbraMax: blur.penumbraMax, depthScale,
    facingFloor: o.facingFloor,
  });
  return {
    mask: out.mask, maskWidth: mw, maskHeight: mh,
    shadowed: out.shadowed, spheres: cameraPass.count,
    filled: atoms && atoms.edges ? Math.floor(atoms.edges.length / 2) : 0,
    strength: o.strength,
    /* THE SHAPES THAT CAST: the balls/capsules, and the REAL triangles — with
       the ring plates called out, since they are what the report asked for (« the
       aromatic rings do not project their hexagons »). */
    triangles: tris ? tris.count : 0,
    trianglesTotal: tris ? (tris.total || tris.count) : 0,
    plates: tris ? tris.plates : 0,
    kinds: tris ? tris.kinds : '',
    strokes: proxyStrokeSummary(atoms && atoms.radii, atoms && atoms.count),
    facing: out.facing,
    blur,
    rig: Number.isFinite(Number(light.width)) && Number.isFinite(Number(light.height))
      ? { width: light.width, height: light.height, depth: light.far - light.near }
      : null,
    penumbra: { taps: out.taps, radius: blur.softness, grow: blur.penumbra, reached: out.penumbraRadius },
  };
};

const defaultDecode = async (blob) => {
  if (typeof createImageBitmap === 'function') return createImageBitmap(blob);
  if (typeof document === 'undefined') throw new Error('no decoder for the still');
  const url = URL.createObjectURL(blob);
  try {
    const img = await new Promise((resolve, reject) => {
      const el = document.createElement('img');
      el.onload = () => resolve(el);
      el.onerror = () => reject(new Error('the still could not be decoded'));
      el.src = url;
    });
    return img;
  } finally {
    setTimeout(() => { try { URL.revokeObjectURL(url); } catch { } }, 4000);
  }
};
const canvasOf = (width, height) => {
  if (typeof OffscreenCanvas === 'function') return new OffscreenCanvas(width, height);
  if (typeof document === 'undefined') throw new Error('no canvas to write the still on');
  const canvas = document.createElement('canvas');
  canvas.width = width; canvas.height = height;
  return canvas;
};
const toPngBlob = (canvas) => new Promise((resolve, reject) => {
  if (typeof canvas.convertToBlob === 'function') {
    canvas.convertToBlob({ type: 'image/png' }).then(resolve, reject);
    return;
  }
  canvas.toBlob((b) => (b ? resolve(b) : reject(new Error('the still could not be encoded'))), 'image/png');
});
export const shadowImageData = (imageData, shadow) => {
  if (!imageData || !shadow || !shadow.mask) return 0;
  return applyShadowToPixels(
    imageData.data, imageData.width, imageData.height,
    shadow.mask, shadow.maskWidth, shadow.maskHeight, shadow.strength,
  );
};
export const addCastShadowsToBlob = async (blob, { shadow, decode = null, encode = null } = {}) => {
  if (!blob || !shadow || !shadow.mask || shadow.applied) return blob;
  try {
    const decodeImage = decode || defaultDecode;
    const canvasWriter = encode || null;
    const src = await decodeImage(blob);
    const width = shadow.imageWidth || (src && (src.width || 0));
    const height = shadow.imageHeight || (src && (src.height || 0));
    if (!width || !height) return blob;
    const canvas = canvasOf(width, height);
    const ctx = canvas.getContext('2d');
    if (!ctx) return blob;
    ctx.drawImage(src, 0, 0, width, height);
    const imageData = ctx.getImageData(0, 0, width, height);
    const hit = shadowImageData(imageData, shadow);
    shadow.reachedPixels = hit;
    if (!hit) return blob;
    ctx.putImageData(imageData, 0, 0);
    const out = canvasWriter ? await canvasWriter(canvas) : await toPngBlob(canvas);
    if (src && typeof src.close === 'function') src.close();
    shadow.applied = true;
    return out || blob;
  } catch (err) {
    shadow.failed = (err && err.message) || 'the still could not be shadowed';
    console.warn('✨ Ray: no cast shadows —', shadow.failed);
    return blob;
  }
};
export const rayShadowNote = (shadow, reason = '') => {
  if (!shadow || !shadow.mask) {
    return reason ? `· no cast shadows — ${reason}` : '';
  }
  if (shadow.failed) return `· no cast shadows — ${shadow.failed}`;
  const pct = Math.round((Number(shadow.strength) || 0) * 100);
  const px = Number(shadow.reachedPixels);
  const covered = Number.isFinite(px) && shadow.imageWidth && shadow.imageHeight
    ? Math.round((px / (shadow.imageWidth * shadow.imageHeight)) * 100)
    : null;
  const spheres = Number(shadow.spheres) || 0;
  const links = Number(shadow.filled) || 0;
  const triangles = Number(shadow.triangles) || 0;
  const plates = Number(shadow.plates) || 0;
  const kinds = triangles && shadow.kinds ? ` · ${shadow.kinds}` : '';
  const f = shadow.facing;
  const faces = f && Number.isFinite(Number(f.mean))
    ? ` · lamp facing ${Number(f.mean).toFixed(2)} (floor ${Number(f.floor).toFixed(2)})`
    : '';
  const st = shadow.strokes;
  const strokes = st && st.list && st.list.length
    ? `· strokes ${st.list.map((e) => `${e.radius.toFixed(2)} Å×${e.hits}`).join(' · ')}${st.rest ? ` · +${st.rest}` : ''}`
    : '';
  const rig = shadow.rig && Number.isFinite(Number(shadow.rig.width))
    ? `· rig ${Math.round(shadow.rig.width)}×${Math.round(shadow.rig.height)} Å`
    : '';
  return `· cast shadows ${pct}%${covered == null ? '' : ` (${covered}% of the pixels)`}`
    + `${spheres ? ` · ${spheres} proxies` : ''}`
    + `${links ? ` · ${links} link capsules` : ''}`
    + `${triangles ? ` · ${triangles} triangles${plates ? ` (${plates} ring plates)` : ''}${kinds}` : ''}`
    + `${faces}${strokes}${rig}`;
};